from pathlib import Path
import hashlib,json
from datetime import datetime,timezone
import psycopg
ROOT=Path('/Users/athena/.codex/.chatgpt-projects/g-p-6ab89116b65c81919bb561fed2d716c0/work/impact-platform');HERE=Path(__file__).resolve().parent
raw=json.loads((HERE/'native-current033-advice-retention-diagnostic.json').read_text());base=json.loads((HERE/'native-corrected02.json').read_text())
out={'recorded_at':datetime.now(timezone.utc).isoformat(),'status':'UNRESOLVED_REGISTERED_0.33_RESIDUAL','scope':'Actual PostgreSQL17.11 SQL visibility diagnostic, not an API or actual privacy expiry workflow. Synthetic storage-valid Open case and expired create/action receipts; immutable/deferred/RLS guards enabled. Both worker calls used savepoint rollback, preserving rows. Unregistered additive0040 exclusion pending registration and integrated requalification. No private identifiers, DSNs, passwords or case text retained in this sanitized report.','database':'Owned disposable portability scratch, schema39 plus unrelated unregistered export draft661a0a18','original_migrations':{str(x['version']):x['sha256'] for x in base['applied_migrations'] if x['version'] in [27,30,38,39]},'actual_six_login_topology':base['checks'][0]['observations']['actual_topology'],'connection_method':'Actual impact_worker_login, SET LOCAL ROLE impact_worker, transaction-local current fixture tenant, no advice participant context','observations':[{'overload_arguments':x['overload_arguments'],'private_operation_keys_returned':len(x['private_case_operation_keys_returned']),'commands':['create_human_advice_case','human_advice_cancel'],'literal_private_keys_omitted':True,'rollback_after_probe':True} for x in raw['observations']],'remedy_candidate':'Exclude current ^(human_advice_|create_human_advice_case$) predicate and new issue_ai_plan_export from both existing key-returning purge definers in additive0040; retain these pointers until a reviewed private retention path. Preserve ordinary expired receipt purge.'}
with psycopg.connect(host='127.0.0.1',port=55437,dbname='impact_test_tola_ai_portability_corrected02',user='tola_fixture',password=Path('/private/tmp/tola-ai-native-build/admin-password').read_text().strip()) as c:
 out['actual_server_version']=c.execute('SHOW server_version').fetchone()[0]
 out['actual_existing_definers']=[{'signature':signature,'definition':definition,'definition_sha256':hashlib.sha256(definition.encode()).hexdigest()} for signature,definition in c.execute("SELECT p.oid::regprocedure::text,pg_get_functiondef(p.oid) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='impact' AND p.proname='retention_purge_receipts' ORDER BY p.pronargs").fetchall()]
 out['all_immutable_rls_deferred_guards_enabled']=c.execute("SELECT bool_and(tgenabled='O') FROM pg_trigger WHERE NOT tgisinternal AND tgname IN ('revision_removal_guard','human_advice_projection_guard','human_advice_head_consistency','human_advice_brief_immutable')").fetchone()[0]
path=ROOT/'docs/evidence/sprint-0.33-human-advice-retention-definer-residual.json';assert not path.exists();path.write_text(json.dumps(out,indent=2)+'\n');print('Saved sanitized current0.33 source-bound residual evidence.')
