"""Regenerate deploy/requirements.runtime.txt from requirements.lock with PyPI SHA-256 hashes.

The container image installs the runtime subset of requirements.lock (the development tools
pytest and ruff and their dependencies are left out) with `pip install --require-hashes`. Every
distribution file PyPI lists for the pinned version is hashed, so pip may choose the wheel that
fits the image. Run it after changing requirements.lock:

    .venv/bin/python deploy/hash_requirements.py

qualification/test_deploy_unit.py fails when the hashed file and the lock disagree on versions.
"""

import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "requirements.lock"
OUTPUT = ROOT / "deploy/requirements.runtime.txt"
# Development-only packages of requirements.lock: the test runner, the linter and their dependencies.
DEVELOPMENT = {"pytest", "ruff", "iniconfig", "pluggy", "pygments", "packaging"}


def canonical(name):
    return name.lower().replace("_", "-").replace(".", "-")


def pins(text):
    result = []
    for line in text.splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        name, version = line.split("==")
        result.append((name.strip(), version.strip()))
    return result


def runtime_pins(text):
    return [(n, v) for n, v in pins(text) if canonical(n) not in DEVELOPMENT]


def hashes(name, version):
    with urllib.request.urlopen("https://pypi.org/pypi/" + name + "/" + version + "/json", timeout=30) as r:
        data = json.load(r)
    return sorted({f["digests"]["sha256"] for f in data["urls"]})


def main():
    lines = [
        "# Generated by deploy/hash_requirements.py from requirements.lock; do not edit by hand.",
        "# Runtime subset installed in the container image with pip --require-hashes.",
    ]
    for name, version in runtime_pins(LOCK.read_text()):
        digests = hashes(name, version)
        if not digests:
            raise RuntimeError("No distribution files on PyPI for " + name + "==" + version)
        lines.append(name + "==" + version + " \\")
        lines.extend(
            "    --hash=sha256:" + d + (" \\" if i < len(digests) - 1 else "") for i, d in enumerate(digests)
        )
    OUTPUT.write_text("\n".join(lines) + "\n")
    print("Wrote " + str(OUTPUT.relative_to(ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
