BEGIN;
SET LOCAL ROLE impact_owner;
CREATE TABLE impact.web_session(session_hash bytea PRIMARY KEY CHECK(octet_length(session_hash)=32),identity_id uuid NOT NULL REFERENCES impact.auth_identity,created_at timestamptz NOT NULL,last_seen_at timestamptz NOT NULL,expires_at timestamptz NOT NULL,auth_time timestamptz NOT NULL,revoked_at timestamptz);
CREATE TABLE impact.login_attempt(attempt_hash bytea PRIMARY KEY CHECK(octet_length(attempt_hash)=32),window_start timestamptz NOT NULL,failures integer NOT NULL CHECK(failures>=0));
CREATE TABLE impact.oidc_login(state_hash bytea PRIMARY KEY CHECK(octet_length(state_hash)=32),browser_hash bytea NOT NULL,nonce text NOT NULL,verifier text NOT NULL,expires_at timestamptz NOT NULL,consumed_at timestamptz);
GRANT SELECT,INSERT,UPDATE,DELETE ON impact.web_session,impact.login_attempt,impact.oidc_login TO impact_identity;
CREATE FUNCTION impact.identity_tenants(requested_identity uuid) RETURNS TABLE(tenant_id uuid) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,impact AS $$ SELECT DISTINCT p.tenant_id FROM impact.tenant_principal p WHERE p.identity_id=requested_identity AND p.active $$;
REVOKE ALL ON FUNCTION impact.identity_tenants(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION impact.identity_tenants(uuid) TO impact_identity;
CREATE POLICY principal_identity_directory ON impact.tenant_principal FOR SELECT TO impact_owner USING(true);
CREATE TABLE impact.object_natural_author(tenant_id uuid NOT NULL,object_id uuid NOT NULL,natural_identity_id uuid NOT NULL,PRIMARY KEY(tenant_id,object_id,natural_identity_id),FOREIGN KEY(tenant_id,object_id) REFERENCES impact.object_registry);
CREATE TABLE impact.result_binding(tenant_id uuid NOT NULL,result_id uuid NOT NULL,indicator_id uuid NOT NULL,period_id uuid NOT NULL,source_digest char(64) NOT NULL,PRIMARY KEY(tenant_id,result_id),FOREIGN KEY(tenant_id,result_id) REFERENCES impact.calculated_result_current(tenant_id,object_id),FOREIGN KEY(tenant_id,indicator_id) REFERENCES impact.indicator_instance_current(tenant_id,object_id),FOREIGN KEY(tenant_id,period_id) REFERENCES impact.period_current(tenant_id,object_id));
ALTER TABLE impact.object_natural_author ENABLE ROW LEVEL SECURITY;
ALTER TABLE impact.object_natural_author FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_fence ON impact.object_natural_author USING(tenant_id=impact.current_tenant()) WITH CHECK(tenant_id=impact.current_tenant());
ALTER TABLE impact.result_binding ENABLE ROW LEVEL SECURITY;
ALTER TABLE impact.result_binding FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_fence ON impact.result_binding USING(tenant_id=impact.current_tenant()) WITH CHECK(tenant_id=impact.current_tenant());
GRANT SELECT,INSERT ON impact.object_natural_author,impact.result_binding TO impact_app;
GRANT SELECT ON impact.schema_migration TO impact_app;
REVOKE UPDATE ON impact.operation_receipt FROM impact_app;
CREATE INDEX grant_by_subject_capability ON impact.grant_current(tenant_id,subject_id,capability,expires_at);
CREATE INDEX registry_type_page ON impact.object_registry(tenant_id,object_type,created_at,object_id);
CREATE INDEX membership_by_identity ON impact.membership_current(tenant_id,identity_id,status);
CREATE INDEX scope_object_lookup ON impact.scope_member(tenant_id,object_id,scope_id);
COMMIT;
