"""Conservative requirement ledger; API presence alone never qualifies a requirement."""

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
catalogue = json.loads((ROOT / "specification/contracts/fsd-requirements.json").read_text())
groups = [
    (
        "FR-TEN-001",
        "v0.10–0.13 implement operator-requested profiles, owner acceptance, independent activation, readiness/impact checks, access fencing and durable work holds. Initial access now requires an owner proposal, separate administrator acceptance and independent operator approval of fixed capability/expiry ceilings; business grants still require separate review. Recovery-contact nomination, registered-account/MFA verification, independent approval, replacement/renewal, revocation and current eligibility now gate activation/reactivation. v0.13 adds reviewed renewal/extension of unexpired delegated authority: the owner pins the exact current ceilings, grants and administrative assignments of both administrators, the second administrator accepts, an independent operator approves within 7 days and within 90 days of expiry, and a database-owned applicator re-dates only the pinned rows. Limits: expired authority is not renewable, tenants without exactly one second administrator are unsupported, and renewal requires current readiness including recovery-contact evidence. Partial: external channel verification/invitations, unavailable-owner recovery, support/exit access, workers, credential rechecks and archival/deletion remain open; native concurrency evidence is limited to the renewal-approval-versus-grant-revocation race in qualification/test_native_concurrency.py (v0.14). v0.16 (qualification/test_worker.py, test_native_worker.py) adds a worker that honours the suspension hold on queued deliveries: a row carrying held_at (what quiesce_tenant sets on suspension; the test sets it directly on an Active tenant) is never sent, a held row whose lease ends returns to PENDING and stays held, and nothing is re-queued on reactivation (no automatic replay, as the validation text requires; no operator re-queue exists); the worker lists Provisioning, Active and Suspended tenants and runs its reminder and cancellation scans for Active tenants only; queued jobs whose cancellation was requested become Cancelled and a started job is recorded NOT_CANCELLED_STARTED, exercised only with test-inserted jobs because no job class is executed; a recovery contact's nominee can confirm the registered email address with a single-use code (15 minutes, 5 attempts, 3 requests per hour), recorded as evidence only — it changes neither readiness nor what a contact may do. Still open: source-credential rechecks on reactivation, a real import and report schedule for the acceptance scenario, support and exit access, closure, and the external email provider.",
        [
            "apps/api/impact_api/tenant_lifecycle.py",
            "qualification/test_tenant_lifecycle.py",
            "tools/browser/tenant-check.mjs",
            "docs/RELEASE-0.10.md",
            "apps/api/impact_api/access_bootstrap.py",
            "qualification/test_access_bootstrap.py",
            "tools/browser/bootstrap-check.mjs",
            "docs/RELEASE-0.11.md",
            "apps/api/impact_api/recovery_contacts.py",
            "qualification/test_recovery_contacts.py",
            "tools/browser/recovery-check.mjs",
            "docs/RELEASE-0.12.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
            "qualification/test_native_concurrency.py",
            "apps/api/impact_api/worker.py",
            "qualification/test_worker.py",
            "qualification/test_native_worker.py",
            "docs/RELEASE-0.16.md",
        ],
    ),
    (
        "FR-IAM-009",
        "Provisioned-identity invitations, membership changes, independent role approval, suspension and revocation are implemented. v0.13 adds reviewed renewal/extension of unexpired delegated authority within the existing ceilings: owner proposal, second-administrator consent and independent operator approval, with no capability widening and no resurrection of revoked grants. v0.15 (#19) narrows what is delegable to capabilities of the 138 implemented operations (84 capabilities): a custom role naming a design-only capability is refused with CAPABILITY_NOT_DELEGABLE at create and at revise even when the creator holds a delegation ceiling for it (test_workspace_administration.py::test_custom_roles_delegate_only_implemented_capabilities), and the orphan create_organisation_units policy row is gone. Custom roles created before v0.15 are not re-checked. Federation assurance, recovery, all identity providers, renewal of expired authority, administrator replacement and full departure inventory are not qualified.",
        [
            "apps/api/impact_api/administration.py",
            "qualification/test_administration.py",
            "docs/RELEASE-0.2.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
            "apps/api/impact_api/contracts.py",
            "apps/api/impact_api/workspace_administration.py",
            "qualification/test_workspace_administration.py",
            "docs/RELEASE-0.15.md",
        ],
    ),
    (
        "FR-IAM-001",
        "Provisioned-identity invitations, membership changes, independent role approval, suspension and revocation are implemented: the inviter chooses tenant, role template, scopes, expiry and the intended verified identity; acceptance requires the nominated verified identity, a valid token and current inviter authority and creates one membership; resend invalidates the earlier link (qualification/test_administration.py). v0.16 adds email delivery of the invitation through the worker (apps/api/impact_api/delivery.py, worker.py; qualification/test_worker.py): creating or resending an invitation records one delivery intent in the same transaction holding no token and no clear address (the address is sealed, the link is re-derived from tenant, invitation and generation when sent); the worker sends the link only while that generation is current, so a resent, revoked, expired or closed invitation's earlier intent becomes SUPERSEDED and is never sent; each intent carries its own delivery state (SENT, retried with backoff, DEAD with an error class such as RECIPIENT_REFUSED or SMTP_PERMANENT_REJECTION), and sending the email creates no membership — acceptance is unchanged. Evidence is on a local SMTP sink and the synthetic sink only. Not covered: bulk invitation outcomes separating created, duplicate, invalid and delivery-failed rows (no bulk invitation exists), the seven-day default expiry as a qualified default, a live email provider with bounces, SPF/DKIM and sending limits, and federation assurance and recovery.",
        [
            "apps/api/impact_api/administration.py",
            "qualification/test_administration.py",
            "docs/RELEASE-0.2.md",
            "apps/api/impact_api/delivery.py",
            "apps/api/impact_api/worker.py",
            "qualification/test_worker.py",
            "docs/RELEASE-0.16.md",
        ],
    ),
    (
        "FR-TEN-003 FR-IAM-002 FR-IAM-006 FR-IAM-008 FR-IAM-013 FR-IAM-014 FR-ACC-003 FR-ACC-006 FR-ACC-012",
        "Provisioned-identity invitations, membership changes, independent role approval, suspension and revocation are implemented. Federation assurance, recovery, all identity providers and full departure inventory are not qualified.",
        [
            "apps/api/impact_api/administration.py",
            "qualification/test_administration.py",
            "docs/RELEASE-0.2.md",
        ],
    ),
    (
        "FR-ACC-001 FR-ACC-002 FR-ACC-004 FR-ACC-005 FR-ACC-011 FR-SEC-004 FR-SEC-007 FR-SEC-012 FR-INT-004 FR-INT-005",
        "Implemented routes enforce explicit grants, tenant fences, natural-person independence, revisions and retry receipts. Native concurrency evidence is limited to the raced approvals, operation replays, close reviews and renewal-versus-revocation cases of qualification/test_native_concurrency.py (v0.14); every future module, audit tamper evidence and production assurance remain open.",
        [
            "apps/api/impact_api/store.py",
            "apps/api/impact_api/auth.py",
            "qualification/test_live_application.py",
        ],
    ),
    (
        "FR-SEC-003",
        "Implemented routes enforce explicit grants, tenant fences, natural-person independence, revisions and retry receipts. v0.14 adds native PostgreSQL evidence for the database side of the fence: the API runs on three separately provisioned login roles (impact_app_login, impact_identity_login, impact_platform_login; NOINHERIT, NOBYPASSRLS, exactly one privilege-role membership each) with IMPACT_REQUIRE_UNPRIVILEGED_DB=1, and qualification/test_native_roles.py proves under those real logins (PostgreSQL 16.13 locally, 17.11 in CI) that each login assumes only its own role, that impact_app reads nothing without a transaction-local tenant and exactly one tenant with one, that it cannot read the control-plane tables, that impact_identity reaches identity tables only, that impact_platform writes only its RESTRICTIVE object types, and that the runtime guard refuses superuser, BYPASSRLS, owner-member and shared logins on every transaction (PRIVILEGED_RUNTIME_CONNECTION, SHARED_RUNTIME_LOGIN) with no login name in any response. The restore drill re-verifies ownership, RLS, policies, grants and the fences on a restored copy. Not covered: attachments, asynchronous jobs, caches, search, AI and support paths (none exist), connection pooling and context reset on pooled connections, audit tamper evidence, an isolation fixture with synthetic tenant markers across every module, and production assurance.",
        [
            "apps/api/impact_api/store.py",
            "apps/api/impact_api/auth.py",
            "qualification/test_live_application.py",
            "scripts/provision_logins.py",
            "qualification/test_native_roles.py",
            "scripts/restore_drill.py",
            "docs/evidence/native-application-tests.xml",
            "docs/evidence/native-qualification.json",
            "docs/RELEASE-0.14.md",
        ],
    ),
    (
        "FR-PLN-006 FR-PRG-001 FR-PRG-005 FR-PRG-006 FR-PRG-007 FR-IND-001 FR-IND-002 FR-IND-005 FR-IND-007 FR-IND-008 FR-IND-009 FR-IND-010 FR-IND-012 FR-DQ-006",
        "Manual FLOW measures, independently approved definitions/plans, reviewed obligation exceptions, eligible assignments, reference selection and programme readiness are implemented. Historical expected, required and excepted counts are preserved. Rich planning, reference administration, automated schedules and the other measurement profiles remain open.",
        ["apps/api/impact_api/measurement.py", "qualification/test_work_center.py", "docs/RELEASE-0.7.md"],
    ),
    (
        "FR-CAL-001 FR-CAL-002 FR-CAL-003 FR-CAL-005 FR-CAL-008 FR-CAL-009 FR-CAL-010 FR-CAL-015 FR-DAT-008 FR-ANA-004",
        "Decimal SUM and pooled ratios, revision-bound lineage, explicit contributor coverage and stale-result flags are implemented. Hierarchy, stock, overlap, weighting, dimensions and production workload qualification are not implemented.",
        [
            "apps/api/impact_api/domain.py",
            "apps/api/impact_api/service.py",
            "qualification/test_measurement.py",
        ],
    ),
    (
        "FR-CAL-011 FR-DAT-009 FR-WFL-001 FR-WFL-002 FR-WFL-003 FR-WFL-004 FR-WFL-010",
        "Single-stage independent review and governed source/plan/assignment amendments are implemented. Affected provisional result revisions receive durable invalidations and personal recalculation work; current approved inputs produce a replacement revision while old lineage remains immutable. Cross-period aggregates, dashboards, reports, distributed artifacts, bulk amendments, configurable multistage policies and escalation remain open.",
        ["apps/api/impact_api/work.py", "qualification/test_work_center.py", "docs/RELEASE-0.7.md"],
    ),
    (
        "FR-WFL-006",
        "A personal work centre implements deduplicated recalculation assignments and safe in-app notices with event identity, acknowledgement and exact-retry protection. v0.16 adds per-recipient delivery status: every notice records an IN_APP delivery intent that the worker delivers exactly once (fenced SENT, one notification_delivery row and a consumer receipt in one transaction; the notice gains delivered_at beside acknowledged_at), a notice for a recipient who is no longer active is SUPERSEDED rather than delivered, and delegated-authority expiry reminders (14 and 3 days) are created once per principal, expiry instant and threshold however often the scan runs (qualification/test_worker.py). Due obligations, returned work, channel preferences, digests, email or push delivery of notices, muting rules for mandatory security notices, failed-delivery remediation flags and escalations remain open.",
        [
            "apps/api/impact_api/work.py",
            "apps/web/src/WorkCenter.tsx",
            "docs/RELEASE-0.7.md",
            "apps/api/impact_api/worker.py",
            "qualification/test_worker.py",
            "docs/RELEASE-0.16.md",
        ],
    ),
    (
        "FR-WFL-007 FR-WFL-008",
        "Programme-period close previews pin plans, sources and provisional results; independently reviewed exclusions remain visible but do not block required completion. Approval creates official results and an immutable versioned snapshot. Scoped, time-bounded restatement preserves and supersedes the original. Optional-late-source policy, distributed-artifact impact and multi-period downstream regeneration remain open.",
        [
            "apps/api/impact_api/period_governance.py",
            "qualification/test_period_governance.py",
            "docs/RELEASE-0.5.md",
        ],
    ),
    (
        "FR-RPT-003 FR-RPT-005 FR-RPT-007 FR-RPT-009 FR-RPT-010",
        "Internal reports bind to a locked snapshot, approved template and official result/evidence revisions. Independent approval records an append-only reconciliation digest. Numeric narrative claims must use known binding placeholders; deterministic semantic HTML and CSV artifacts are frozen for an independently reviewed, named-recipient, expiring disclosure and every view/download is logged. Withdrawal closes access without deleting artifacts or history. Charts, PDF/DOCX/XLSX, anonymous publication, delivery, supersession notices and distributed-artifact handling remain open.",
        [
            "apps/api/impact_api/reporting.py",
            "qualification/test_reporting.py",
            "qualification/test_publication.py",
            "docs/RELEASE-0.6.md",
            "docs/RELEASE-0.8.md",
        ],
    ),
    (
        "FR-RPT-004 FR-UX-001 FR-UX-002 FR-UX-003 FR-UX-004 FR-UX-005 FR-UX-009",
        "Browser workspaces, labelled dialogs, bound narrative authoring, controlled-publication actions, explicit status and health endpoints are implemented. Full accessibility/usability qualification, anonymous publication, service monitoring and all remaining screens are open.",
        ["apps/web/src/main.tsx", "tools/browser/reporting-check.mjs", "docs/IMPLEMENTATION.md"],
    ),
    (
        "FR-OPS-005",
        "Browser workspaces, labelled dialogs, bound narrative authoring, controlled-publication actions, explicit status and health endpoints are implemented. v0.14 adds to the health surface: with unprivileged connections required, /health/ready first verifies that the app, identity and platform connections are three distinct unprivileged logins and answers 503 with a reason code only (PRIVILEGED_RUNTIME_CONNECTION, SHARED_RUNTIME_LOGIN, PLATFORM_NOT_CONFIGURED; no login name reaches a response), the same check refuses every transaction, and the native restart check shows readiness and the runtime manifest unchanged across an API restart. Service monitoring proper remains open: no health view separated by component, no journey success, latency, backlog, freshness or quota measurement, no incident record, no tenant-cohort view, no metrics, log pipeline or alerting exists; full accessibility/usability qualification, anonymous publication and all remaining screens are also open.",
        [
            "apps/web/src/main.tsx",
            "tools/browser/reporting-check.mjs",
            "docs/IMPLEMENTATION.md",
            "apps/api/impact_api/main.py",
            "apps/api/impact_api/store.py",
            "qualification/test_native_roles.py",
            "qualification/test_native_restart.py",
            "docs/evidence/native-qualification.json",
            "docs/RELEASE-0.14.md",
        ],
    ),
    (
        "VF-DIN-002",
        "Native PostgreSQL only (qualification/test_native_concurrency.py, 11 cases, executed on PostgreSQL 16.13 in the workspace on 29 September 2026 and 17.11 in CI; skipped on PGlite, whose single process lock cannot contend): two independent reviewers approving one candidate revision at once admit exactly one decision (200 and CONFLICT_VERSION; one new revision each of candidate and workflow, one audit event, one outbox event, one receipt); the same command from two threads returns the one receipt and writes one revision; the same operation identifier with different payloads admits exactly one (CONFLICT_OPERATION for the other); two independent close reviews of one period produce one OFFICIAL snapshot version and PERIOD_ALREADY_SNAPSHOTTED for the other; a renewal approval raced with a pinned-grant revocation in both orders yields either the renewed set with the stale revocation refused (CONFLICT_VERSION) or the revoked grant with the approval refused (AUTHORITY_CHANGED), never both; ten reads complete beside a held tenant advisory lock while a write queues, and a write held past lock_timeout is refused with no receipt. Not covered: two concurrent edits of one record, repeated import commands and interrupted bulk jobs (no import or bulk job exists), the LLD lock order across objects under concurrent writers (the mixed-write case is a no-regression smoke test), connection pooling, and any load profile. The target's recoverable explicit partial outcomes exist only where an operation defines them.",
        [
            "qualification/test_native_concurrency.py",
            "apps/api/impact_api/service.py",
            "apps/api/impact_api/store.py",
            "docs/evidence/native-application-tests.xml",
            "docs/evidence/native-qualification.json",
            "docs/RELEASE-0.14.md",
        ],
    ),
    (
        "VF-DR-003",
        "A scripted, verified restore exists and has been executed (scripts/restore_drill.py; 29 September 2026 on PostgreSQL 16.13, and in the CI native job on 17.11 for commit c759e9e): pg_dump -Fc of the qualification database (3,427,234 bytes in 0.45 s), pg_restore into a sibling database (1.56 s), a migrator checksum pass that applies nothing and verifies all 16 ledgered checksums, the seeded OFFICIAL 46.36 present in its snapshot revision with its payload hash, equal row counts in all 151 impact tables (30,016 rows), identical ownership, RLS flags, policies, functions and grants, the tenant fences and control-plane denials intact for impact_app, and no credential altered. This is a CI-scale restore drill of a disposable qualification database, not a backup regime: no scheduled backup, retention window, off-site or immutable copy, protection against alteration or credential compromise, monthly restore cadence, quarterly disaster exercise, key recovery, attachment integrity (no attachments exist) or deletion/restriction replay before reopening exists, and no RPO or RTO is established. A restore of a production-scale database is not qualified.",
        [
            "scripts/restore_drill.py",
            "docs/evidence/native-restore-drill.json",
            "docs/evidence/native-qualification.json",
            "docs/RELEASE-0.14.md",
            "docs/current/OPERATIONS-GUIDE.md",
        ],
    ),
    (
        "FR-TEN-002 FR-TEN-010 FR-IAM-003 FR-IAM-006 FR-IAM-008 FR-IAM-010 FR-IAM-013 FR-ACC-002",
        "v0.9 adds versioned custom roles, independently reviewed flat group access, immediate organisation moves with cycle checks, renewal without old-access resurrection, nominated custody transfer, self-service session revocation/preferences and configured ACR enforcement. v0.13 adds reviewed renewal/extension of unexpired delegated authority (owner proposal pinning the exact current ceilings, second-administrator acceptance, independent operator approval, database-owned re-dating of only the pinned rows); expired authority is not renewable and single-administrator tenants are unsupported. Further onboarding acceptance, provider MFA/recovery qualification, action-bound step-up, future-effective organisation impact and full access certification remain open.",
        [
            "apps/api/impact_api/workspace_administration.py",
            "apps/api/impact_api/account.py",
            "qualification/test_workspace_administration.py",
            "tools/browser/workspace-check.mjs",
            "docs/RELEASE-0.9.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
        ],
    ),
    (
        "FR-IAM-002",
        "Provisioned-identity invitations, membership changes, independent role approval, suspension and revocation are implemented. v0.15 qualifies the login binding against a live provider (Keycloak 26.7.4, development mode, in-memory database, qualification/test_live_idp.py: 16 cases on PGlite and 16 on native PostgreSQL 16.13 login roles, 29 September 2026): sign-in binds the provider issuer and stable subject to the fixture identity (the fixture's auth_identity rows are re-pointed to the realm issuer by subject); tokens of another issuer (a second realm of the same provider with the same client and an author user), a tampered signature, a key outside the provider JWKS, an expired token, an ID token presented as a bearer credential (typ check) and provider role claims are refused or confer nothing; a disabled provider account cannot sign in; missing assurance fails safely (a password-only session is refused every fresh-assurance operation). Not covered: an administrator-facing provider configuration, tenant binding and designated-account test mode, certificate or key expiry display and overlapping rotation, provider interruption, emergency local recovery, SAML or any provider other than one Keycloak realm, and a managed or customer-provided provider.",
        [
            "apps/api/impact_api/administration.py",
            "qualification/test_administration.py",
            "docs/RELEASE-0.2.md",
            "apps/api/impact_api/auth.py",
            "scripts/idp.py",
            "tools/idp/qualification-realm.json",
            "qualification/test_live_idp.py",
            "docs/evidence/idp-tests.xml",
            "docs/evidence/idp-native-tests.xml",
            "docs/evidence/idp-qualification.json",
            "docs/RELEASE-0.15.md",
        ],
    ),
    (
        "FR-IAM-003",
        "v0.9 adds versioned custom roles, independently reviewed flat group access, immediate organisation moves with cycle checks, renewal without old-access resurrection, nominated custody transfer, self-service session revocation/preferences and configured ACR enforcement. v0.13 adds reviewed renewal/extension of unexpired delegated authority (owner proposal pinning the exact current ceilings, second-administrator acceptance, independent operator approval, database-owned re-dating of only the pinned rows); expired authority is not renewable and single-administrator tenants are unsupported. v0.15 exercises step-up against a live provider: the qualification realm's browser flow is level 1 password and level 2 TOTP with an ACR map, the platform requests urn:impact:acr:mfa with max_age=0, a session at the password level reads normally but is refused every tenant and account fresh-assurance operation, a user without a second factor is sent to TOTP enrolment before any code is issued, and after TOTP a fresh-assurance operation succeeds until 300 s after the provider's own auth_time (FRESH_AUTHENTICATION_REQUIRED at 301 s, emulated by moving the recorded auth_time back) in qualification/test_live_idp.py and the idp-browser check. Not covered: completion of enrolment, passkeys, a challenge bound to the intended action (step-up is per session, not per pending action), blocking removal of the last qualifying factor, SMS exclusion, authenticator synchronisation disclosure and provider-side recovery.",
        [
            "apps/api/impact_api/workspace_administration.py",
            "apps/api/impact_api/account.py",
            "qualification/test_workspace_administration.py",
            "tools/browser/workspace-check.mjs",
            "docs/RELEASE-0.9.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
            "apps/api/impact_api/auth.py",
            "scripts/idp.py",
            "tools/idp/qualification-realm.json",
            "qualification/test_live_idp.py",
            "docs/evidence/idp-tests.xml",
            "docs/evidence/idp-native-tests.xml",
            "docs/evidence/idp-qualification.json",
            "docs/RELEASE-0.15.md",
            "tools/browser/idp-check.mjs",
            "docs/evidence/idp-browser-tests.json",
        ],
    ),
    (
        "FR-IAM-006",
        "v0.9 adds versioned custom roles, independently reviewed flat group access, immediate organisation moves with cycle checks, renewal without old-access resurrection, nominated custody transfer, self-service session revocation/preferences and configured ACR enforcement. v0.13 adds reviewed renewal/extension of unexpired delegated authority (owner proposal pinning the exact current ceilings, second-administrator acceptance, independent operator approval, database-owned re-dating of only the pinned rows); expired authority is not renewable and single-administrator tenants are unsupported. v0.15 adds live-provider logout (qualification/test_live_idp.py, qualification/test_backchannel_logout.py, idp-browser check): POST /auth/logout revokes the server session at once (the old cookie then gets 401) and returns the provider end-session URL with a sealed id_token_hint, after which the provider session is gone (prompt=none returns login_required); a logout after idle or absolute timeout still clears the cookie; a verified back-channel logout token revokes exactly the platform sessions of that provider session and a replayed token is refused. Server authority is therefore invalidated independently of what the browser still shows. Not covered: clearing in-memory client state and cached navigation, browser back and a queued export from a revoked session (no export job exists), shared-device mode, the idle warning that preserves drafts, and bearer access tokens, which remain valid until exp (120 s in the realm) after a provider logout.",
        [
            "apps/api/impact_api/workspace_administration.py",
            "apps/api/impact_api/account.py",
            "qualification/test_workspace_administration.py",
            "tools/browser/workspace-check.mjs",
            "docs/RELEASE-0.9.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
            "apps/api/impact_api/auth.py",
            "scripts/idp.py",
            "tools/idp/qualification-realm.json",
            "qualification/test_live_idp.py",
            "docs/evidence/idp-tests.xml",
            "docs/evidence/idp-native-tests.xml",
            "docs/evidence/idp-qualification.json",
            "docs/RELEASE-0.15.md",
            "qualification/test_backchannel_logout.py",
            "tools/browser/idp-check.mjs",
            "docs/evidence/idp-browser-tests.json",
        ],
    ),
    (
        "FR-PLN-001",
        "v0.18 implements typed framework nodes (IMPACT, OUTCOME, OUTPUT, ACTIVITY) with stable node identities, title, description, owner and indicator placement in one governed framework per programme, edited in a table with a hierarchy tree (apps/web/src/Planning.tsx). Validation exercised by executed tests (qualification/test_planning.py::test_hierarchy_structure_is_refused, test_unmeasured_output_blocks_submission_until_documented_exception, test_planning_unit.py::test_structure_rules): containment cycles, including a node containing itself, orphaned parent references and deletion of a node that places indicators in the approved baseline (NODE_REFERENCED) are rejected on every save, as are level inversions and indicators placed twice or from another programme; renaming an output in a draft keeps its node identity and indicator placement (test_framework_draft_review_baseline_and_child_version). Not covered: a relationship (graph) view editing the same identities, relationship links and numeric aggregation links as distinct objects (theory-of-change relationships are accepted only empty and assumption or input nodes are refused), activity-to-output links beyond containment, and the graph half of the acceptance scenario.",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "apps/web/src/Planning.tsx",
            "tools/browser/planning-check.mjs",
            "docs/evidence/native-application-tests.xml",
            "docs/evidence/planning-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
        ],
    ),
    (
        "FR-PLN-003",
        "v0.18 submits a framework with its completeness report, shows the reviewer the candidate with that report and, for a child draft, the superseded revision and a comparison (nodes added, removed, changed); approval by an independent natural person freezes a baseline version in the insert-only framework_baseline register, and a later change is a child draft with an effective date that supersedes exactly one approved revision (test_framework_draft_review_baseline_and_child_version, test_second_framework_child_is_refused_after_the_first_is_approved, test_native_planning_registers_are_fenced_and_insert_only). Validation exercised: a period close pins the governing framework revision (the latest baseline effective before the period ends) into the snapshot, and a later approved revision does not re-place the locked period (test_close_pins_governing_framework_revision); the first baseline keeps its approved wording after a July revision. Not covered: the review listing impacted targets, activities, templates and obligations; regeneration of an earlier report against its original hierarchy and language (reports do not bind a framework); deletion of an obsolete draft (no delete operation exists).",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "apps/api/impact_api/period_governance.py",
            "docs/evidence/native-application-tests.xml",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
        ],
    ),
    (
        "FR-PLN-010",
        "v0.18 implements a completeness view listing orphan nodes, unmeasured impact/outcome/output nodes, missing owners and incomplete nodes, and programme indicators not placed on any node, each with severity, rule, object and assigned resolver. Validation and acceptance exercised (test_unmeasured_output_blocks_submission_until_documented_exception, test_exception_authorship_and_review_date): structural invalidity is refused on save and can never be excepted, an exception that matches no current warning becomes an error, submission of a framework with an unmeasured output stays blocked (FRAMEWORK_INCOMPLETE) with an assigned resolver until a documented exception with a reason and a review date not in the past is recorded, the server stamps who recorded it, and the accepted exceptions remain visible in the approved baseline revision; the independent approver of that revision is recorded in the register. Not covered: invalid sources, unreviewed assumptions and conflicting reporting obligations (no such checks), unsupported official arithmetic as a completeness rule, and acceptance by a separately named authority per exception (the approver of the revision is the authority; no per-exception acceptance record exists).",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "tools/browser/planning-check.mjs",
            "docs/evidence/planning-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
        ],
    ),
    (
        "FR-IND-003",
        "v0.18 implements targets and baselines per indicator instance and programme period with target kind (VALUE, RANGE, MILESTONE), value and explicit value state, direction (higher, lower, within range, milestone), basis (original, baseline, revised) and the pinned approved definition revision (its unit); revised targets and baseline corrections supersede the approved revision with a reason, and targets versus actuals shows the selected target's basis and binding version. Validation and acceptance exercised (test_planning_unit.py::test_higher_target_attainment_is_uncapped, test_lower_target_reports_signed_deviation_without_inverting_success, test_zero_target_and_zero_baseline_are_undefined_not_divided; test_planning.py::test_targets_baselines_milestones_and_provisional_progress): actual 120 against a higher target of 100 is 120.00 percent attainment, uncapped; a lower target of 10 with actual 8 is ACHIEVED with deviation -2; a zero target gives Undefined attainment (ZERO_TARGET) rather than a division, and milestones need an assessment. Not covered: a reviewed difference logic for zero targets, status thresholds, disaggregated and cumulative targets, measurement dates other than a programme period, and restated comparisons after close (FR-IND-004).",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "apps/web/src/Planning.tsx",
            "tools/browser/planning-check.mjs",
            "docs/evidence/planning-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
        ],
    ),
    (
        "FR-ANA-003",
        "v0.18 implements one comparison view, the targets-versus-actuals table (GET /programmes/{id}/targets-vs-actuals and the Targets vs actuals tab), binding the actual, the baseline and the selected target revision with its direction, basis (original or revised), binding version and period; the actual's source is shown (OFFICIAL only from the programme's own locked snapshot, PROVISIONAL from its own calculations) and overachievement stays visible. Validation and acceptance exercised (test_planning_unit.py::test_zero_target_and_zero_baseline_are_undefined_not_divided, test_negative_baseline_has_no_percentage_change, test_lower_target_reports_signed_deviation_without_inverting_success; test_planning.py::test_targets_baselines_milestones_and_provisional_progress, test_period_close_pins_targets_and_uses_official_result): a zero or negative baseline gives an Undefined percentage change (NON_POSITIVE_BASELINE), never an infinite trend, and a lower-is-better target of 10 with actual 8 shows ACHIEVED and the declared deviation without inverting success. Not covered: charts, widgets and axis scales, cumulative curves (no cumulative target exists, so the cumulative-to-flow conversion rule is untested), and time semantics beyond one period.",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "apps/web/src/Planning.tsx",
            "tools/browser/planning-check.mjs",
            "docs/evidence/planning-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
        ],
    ),
    (
        "VF-DIN-001",
        "v0.19 adds a versioned golden corpus (qualification/golden/calculation-corpus-v1.json, corpus 1.1.0, 40 hand-prepared vectors covering CAL01, CAL02, CAL05, CAL06, CAL07, CAL09, CAL16 and CAL20 plus rounding boundaries, magnitude, missingness, invalid input and dimensions) and a reconciliation harness (qualification/test_golden.py, make golden) that compares an independent exact-rational reference with the hand-prepared values, then the domain code and the live API path with the reference, on raw stored and displayed decimals per total and per category; every executed vector passes (docs/evidence/golden-reconciliation.json). Not covered: CAL03, CAL04, CAL10-CAL15, CAL17-CAL19 (overlap, hierarchy, conversions, targets, weighting, currency, cost and disclosure are not implemented or not in the corpus), correction, version and permission variants of each vector, and report bindings.",
        [
            "apps/api/impact_api/domain.py",
            "apps/api/impact_api/calculation_contracts.py",
            "apps/api/impact_api/service.py",
            "qualification/test_calculation_methods.py",
            "qualification/test_golden.py",
            "qualification/golden/calculation-corpus-v1.json",
            "docs/evidence/golden-reconciliation.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.19.md",
        ],
    ),
    (
        "FR-IND-006",
        "v0.19 lets an indicator definition pin a versioned disaggregation scheme (up to five dimensions with code, label, version, multiselect and exhaustive flags and declared category codes; UNSPECIFIED reserved) and observations carry codes checked against it at draft, submission, amendment and calculation; results carry per-category values computed from source rows. Validation and acceptance exercised (test_calculation_methods.py::test_multiselect_categories_are_nonadditive_and_unique_total_stays_one, test_observation_codes_must_match_the_pinned_scheme, test_category_correction_through_change_request; corpus FT-IND-006-multiselect): one contribution with two selected categories counts in both, the total stays one and the categories are labelled NONADDITIVE. Not covered: applicability rules, explicit missing/unknown/declined codes beyond what a scheme declares, reviewed crosswalks for a changed scheme (FR-CAL-007), unique-participant totals (no participants exist), and dimension version validation (free text).",
        [
            "apps/api/impact_api/domain.py",
            "apps/api/impact_api/calculation_contracts.py",
            "apps/api/impact_api/service.py",
            "qualification/test_calculation_methods.py",
            "qualification/test_golden.py",
            "qualification/golden/calculation-corpus-v1.json",
            "docs/evidence/golden-reconciliation.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.19.md",
        ],
    ),
    (
        "FR-FRM-001",
        "v0.20 adds a form builder whose fields live inside the governed Form revision: stable field_id and code, position, type (TEXT, DECIMAL, INTEGER, BOOLEAN, SINGLE_CHOICE), label, help, required, numeric bounds, text length, choices, and an optional indicator binding with value role or a disaggregation dimension; submitting for review locks the exact revision and starts the independent approval, and publication is a separate fresh-assurance action into the insert-only form_publication register. Validation text exercised (test_forms.py::test_form_definition_validation, test_exhaustive_dimension_field_must_be_answered_with_the_value, test_numerator_and_denominator_answers_pool_into_a_percentage, test_form_review_requires_independence_and_publish_requires_approval; forms-browser design step): unsupported combinations (choices on a non-choice field, bounds on a text field, inverted bounds, duplicate codes, a binding on a text field or to a non-manual or foreign indicator, a ratio without both components, an undeclared or multiselect dimension, an optional or differently relevant exhaustive-dimension field) are rejected before publishing. Not covered: groups and repeat groups (100 repeat entries, two nesting levels), field classification, preview in desktop and mobile modes, calculated fields, photos and the 200-question load qualification (the contract caps 200 fields; no test at that size); FT-FRM-001 (household members, photo, calculated age) is not executable.",
        [
            "apps/api/impact_api/forms.py",
            "apps/api/impact_api/forms_contracts.py",
            "apps/web/src/Forms.tsx",
            "infrastructure/migrations/0021_web_forms.sql",
            "qualification/test_forms.py",
            "tools/browser/forms-check.mjs",
            "docs/evidence/forms-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.20.md",
        ],
    ),
    (
        "FR-FRM-002",
        "v0.20 implements one bounded relevance rule per field (relevant_when: an earlier yes/no or choice field equals a declared code), typed by reference to an earlier field and a declared code so that cycles and forward or undeclared references are refused (FORM_RELEVANCE_INVALID); the server evaluates the same versioned rules in field order and the web client uses the same rule to show or hide a question. Validation text exercised (test_forms.py::test_submission_refuses_incomplete_and_hidden_answers, test_draft_answers_are_validated_against_the_version, test_form_definition_validation, test_blank_answers_keep_explicit_value_states; forms-browser fill-in step): a tampered payload carrying an answer to a hidden field is refused (ANSWER_NOT_RELEVANT), a relevant required answer cannot be omitted, a hidden bound field becomes NOT_APPLICABLE. Not covered: a bounded expression catalogue beyond equality, required rules separate from relevance, the visible confirmation and declared policy for clearing newly irrelevant values (the client hides them and the server refuses them), explicitly retained hidden values, and references to inaccessible fields (fields have no classification).",
        [
            "apps/api/impact_api/forms.py",
            "apps/api/impact_api/forms_contracts.py",
            "apps/web/src/Forms.tsx",
            "infrastructure/migrations/0021_web_forms.sql",
            "qualification/test_forms.py",
            "tools/browser/forms-check.mjs",
            "docs/evidence/forms-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.20.md",
        ],
    ),
    (
        "FR-FRM-003",
        "v0.20 moves a form through draft, independent review and publication (no isolated test stage); each publication appends a version to the insert-only form_publication register pinning the approved revision, and a submission retains the exact published form revision it was captured on (form_version required at creation and immutable). Validation and acceptance exercised (test_forms.py::test_superseded_version_quarantines_rather_than_inventing_answers, test_form_version_review_publication_and_submission_to_calculation, test_submission_draft_requires_a_form_version, test_native_form_publication_register_is_fenced_and_insert_only): after a new version with a new mandatory question is published, a response captured on the earlier version is preserved unchanged and quarantined (FORM_VERSION_SUPERSEDED) with no observations rather than completed or mapped. Not covered: compatibility declarations and acceptance cutoffs (only LOCK_PUBLISHED, so every older version is quarantined), reviewed mapping of quarantined responses, translation versions, revocation of an unsafe form, isolated test, and the offline-package scenario of FT-FRM-003 (no offline collection exists).",
        [
            "apps/api/impact_api/forms.py",
            "apps/api/impact_api/forms_contracts.py",
            "apps/web/src/Forms.tsx",
            "infrastructure/migrations/0021_web_forms.sql",
            "qualification/test_forms.py",
            "tools/browser/forms-check.mjs",
            "docs/evidence/forms-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.20.md",
        ],
    ),
    (
        "FR-FRM-006",
        "v0.20 saves server drafts of a response and resumes them with the same submission identity and pinned form version; submit validates the response against that version and returns a receipt, turning each bound indicator into a FORM-namespace observation submitted into the existing independent review in the same transaction. Validation text exercised (forms-browser fill-in step: the submit response is dropped and the retry with the same operation identifier resolves to the original receipt and one submission; test_forms.py::test_form_and_submission_access_boundaries for stale revisions and server-owned fields, test_response_drafters_are_authors_of_its_observations, test_bound_form_submit_requires_observation_submit). Not covered: local (browser) drafts and the indication of where a draft was saved beyond the server confirmation, the unsaved-changes warning, confirmation of intended finality as a separate step, a confirmation-pending state distinct from a retry, and returned work starting a linked correction revision (the FORM namespace is reserved and no submission correction exists).",
        [
            "apps/api/impact_api/forms.py",
            "apps/api/impact_api/forms_contracts.py",
            "apps/web/src/Forms.tsx",
            "infrastructure/migrations/0021_web_forms.sql",
            "qualification/test_forms.py",
            "tools/browser/forms-check.mjs",
            "docs/evidence/forms-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.20.md",
        ],
    ),
    (
        "FR-CAL-001 FR-CAL-003 FR-CAL-005 FR-CAL-008 FR-CAL-009 FR-CAL-010",
        "Decimal calculation with a bounded method catalogue (v0.19): SUM and POOLED_RATIO for FLOW, COUNT for EVENT, LAST_VALID for STOCK and CUMULATIVE (latest approved position; a tie with different values and a cumulative decline give UNDEFINED), labelled unweighted MEAN, MEDIAN, MIN and MAX; methods bound to measurement types and time semantics and refused at definition submission otherwise; 100-digit arithmetic, stored value half-up at 12 places and display derived from the stored value; absent value states never zero; revision-bound lineage, coverage and stale flags as before. Exercised by the golden corpus through reference, domain and live API (CAL01 51/110 = 46.36, CAL02 labelled 30, CAL05 end 20 not 45, CAL06 zero denominator UNDEFINED, CAL07 60.00 coverage, CAL09 1.005 to 1.01, CAL20 boundary) and test_calculation_methods.py. Not covered: cumulative increments (no verified baseline), maximum stock age, hierarchy, overlap, unit conversion, weighting and production workload qualification.",
        [
            "apps/api/impact_api/domain.py",
            "apps/api/impact_api/calculation_contracts.py",
            "apps/api/impact_api/service.py",
            "qualification/test_calculation_methods.py",
            "qualification/test_golden.py",
            "qualification/golden/calculation-corpus-v1.json",
            "docs/evidence/golden-reconciliation.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.19.md",
        ],
    ),
]
# Requirements that stay PENDING, with what the latest increments do and do not show for them.
pending_notes = {
    "FR-IAM-007": "PENDING. Related v0.16 evidence, recorded so that it is not mistaken for coverage: the nominee of a recovery contact can confirm the registered email address with a single-use eight-digit code (channel-request/channel-confirm; 15-minute expiry, 5 attempts, at most 3 requests per contact per hour; the code is derived, never stored, and only its keyed hash is kept; qualification/test_worker.py). That verifies a channel for contact evidence only; it is not an identity change, a lost-factor recovery or a support path, and no test exercises the validation text (no support reset refusal, no restricted recovery case, no withheld privileges pending verification). Retain the original acceptance criteria; this requirement remains open.",
    "FR-ACC-008": "PENDING. Not touched by v0.16 although the delivery plan listed it for that increment: no support case, elevation grant, support session or tenant-ended access exists. The v0.16 worker runs on its own login and writes reminder notices as a per-tenant SERVICE principal without identity, membership or grant; that is not support access. Retain the original acceptance criteria; this requirement remains open.",
    "VF-IAM-001": "PENDING. v0.15 revokes browser sessions immediately on logout and on a verified back-channel logout token (qualification/test_live_idp.py, test_backchannel_logout.py), but the 60-second bound is not met or measured: bearer access tokens remain valid until exp (120 s in the qualification realm) after a provider logout, no revocation latency is measured from platform receipt, and suspension, grant removal, service credentials, generated downloads, search, AI and queued jobs are not polled (most of them do not exist). v0.16's worker re-reads each delivery intent immediately before sending and supersedes it when the invitation generation, the recovery-channel challenge or the notice recipient is no longer current (qualification/test_worker.py); that is a recheck of the intent, not a measured revocation bound, and no sensitive job class exists for the worker to reauthorise. Retain the original acceptance criteria; this requirement remains open.",
}
partial = {key: (description, evidence) for ids, description, evidence in groups for key in ids.split()}
requirements = []
for group in ["functional", "nonfunctional"]:
    for req in catalogue[group]:
        description, evidence = partial.get(
            req["id"],
            (
                pending_notes.get(
                    req["id"],
                    "No complete implementation and acceptance evidence mapped. Retain the original acceptance criteria; this requirement remains open.",
                ),
                [],
            ),
        )
        requirements.append(
            {
                **req,
                "category": group,
                "status": "PARTIAL" if req["id"] in partial else "PENDING",
                "assessment": description,
                "evidence_paths": evidence,
                "release_gate": "Complete the original acceptance criteria and record passing implementation and qualification evidence.",
            }
        )
assert len(requirements) == 307 and len({r["id"] for r in requirements}) == 307
assert set(partial) <= {r["id"] for r in requirements}
assert not set(pending_notes) & set(partial)
for requirement in requirements:
    for path in requirement["evidence_paths"]:
        assert (ROOT / path).is_file(), path
summary = dict(Counter(r["status"] for r in requirements))
result = {
    "build": json.loads((ROOT / "VERSION.json").read_text())["build"],
    "assessment_date": "2026-09-30",
    "enterprise_complete": False,
    "method": "PARTIAL means tested behavior exists for a bounded subset; PENDING does not imply that a scaffold or design contract is an implementation. No enterprise acceptance is inferred from passing subset tests.",
    "summary": summary,
    "requirements": requirements,
}
(ROOT / "docs/COMPLETION-LEDGER.json").write_text(json.dumps(result, indent=2) + "\n")
lines = [
    "# Requirement completion ledger",
    "",
    result["method"],
    "",
    f"Scope: 270 functional requirements and 37 non-functional qualification requirements. Status: {summary}. Enterprise completion: **false**.",
    "",
    "| Requirement | Title | Status | Evidence |",
    "|---|---|---|---|",
]
for req in requirements:
    paths = ", ".join(f"[{Path(p).name}](../{p})" for p in req["evidence_paths"])
    lines.append(f"| {req['id']} | {req['title']} | {req['status']} | {paths or 'Pending'} |")
(ROOT / "docs/COMPLETION-LEDGER.md").write_text("\n".join(lines) + "\n")
print(json.dumps(summary))
