"""Conservative requirement ledger; API presence alone never qualifies a requirement."""

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
catalogue = json.loads((ROOT / "specification/contracts/fsd-requirements.json").read_text())
groups = [
    (
        "FR-TEN-001",
        "v0.10–0.13 implement operator-requested profiles, owner acceptance, independent activation, readiness/impact checks, access fencing and durable work holds. Initial access now requires an owner proposal, separate administrator acceptance and independent operator approval of fixed capability/expiry ceilings; business grants still require separate review. Recovery-contact nomination, registered-account/MFA verification, independent approval, replacement/renewal, revocation and current eligibility now gate activation/reactivation. v0.13 adds reviewed renewal/extension of unexpired delegated authority: the owner pins the exact current ceilings, grants and administrative assignments of both administrators, the second administrator accepts, an independent operator approves within 7 days and within 90 days of expiry, and a database-owned applicator re-dates only the pinned rows. Limits: expired authority is not renewable, tenants without exactly one second administrator are unsupported, and renewal requires current readiness including recovery-contact evidence. Partial: external channel verification/invitations, unavailable-owner recovery, support/exit access, workers, credential rechecks and archival/deletion remain open; native concurrency evidence is limited to the renewal-approval-versus-grant-revocation race in qualification/test_native_concurrency.py (v0.14). v0.16 (qualification/test_worker.py, test_native_worker.py) adds a worker that honours the suspension hold on queued deliveries: a row carrying held_at (what quiesce_tenant sets on suspension; the test sets it directly on an Active tenant) is never sent, a held row whose lease ends returns to PENDING and stays held, and nothing is re-queued on reactivation (no automatic replay, as the validation text requires; no operator re-queue exists); the worker lists Provisioning, Active and Suspended tenants and runs its reminder and cancellation scans for Active tenants only; queued jobs whose cancellation was requested become Cancelled and a started job is recorded NOT_CANCELLED_STARTED, exercised only with test-inserted jobs because no job class is executed; a recovery contact's nominee can confirm the registered email address with a single-use code (15 minutes, 5 attempts, 3 requests per hour), recorded as evidence only — it changes neither readiness nor what a contact may do. Quality 2026-10 (qualification/test_delivery_requeue.py) adds an operator-only, fresh-assurance, reasoned re-queue of a DEAD delivery and release of a held one for an Active tenant, each a separate recorded platform decision (platform_event and receipt), refused while the tenant is Suspended; nothing is replayed automatically. Still open: source-credential rechecks on reactivation, a real import and report schedule for the acceptance scenario, support and exit access, closure, and the external email provider.",
        [
            "apps/api/impact_api/tenant_lifecycle.py",
            "qualification/test_tenant_lifecycle.py",
            "tools/browser/tenant-check.mjs",
            "docs/RELEASE-0.10.md",
            "apps/api/impact_api/access_bootstrap.py",
            "qualification/test_access_bootstrap.py",
            "tools/browser/bootstrap-check.mjs",
            "docs/RELEASE-0.11.md",
            "apps/api/impact_api/recovery_contacts.py",
            "qualification/test_recovery_contacts.py",
            "tools/browser/recovery-check.mjs",
            "docs/RELEASE-0.12.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
            "qualification/test_native_concurrency.py",
            "apps/api/impact_api/worker.py",
            "qualification/test_worker.py",
            "qualification/test_native_worker.py",
            "docs/RELEASE-0.16.md",
            "apps/api/impact_api/delivery_operations.py",
            "qualification/test_delivery_requeue.py",
            "docs/QUALITY-2026-10.md",
            "tools/browser/requeue-check.mjs",
            "docs/evidence/requeue-browser-tests.json",
            "docs/QA-BROWSER-2026-10.md",
        ],
    ),
    (
        "FR-IAM-009",
        "Provisioned-identity invitations, membership changes, independent role approval, suspension and revocation are implemented. v0.13 adds reviewed renewal/extension of unexpired delegated authority within the existing ceilings: owner proposal, second-administrator consent and independent operator approval, with no capability widening and no resurrection of revoked grants. v0.15 (#19) narrows what is delegable to capabilities of the 138 implemented operations (84 capabilities): a custom role naming a design-only capability is refused with CAPABILITY_NOT_DELEGABLE at create and at revise even when the creator holds a delegation ceiling for it (test_workspace_administration.py::test_custom_roles_delegate_only_implemented_capabilities), and the orphan create_organisation_units policy row is gone. Custom roles created before v0.15 are not re-checked. Federation assurance, recovery, all identity providers, renewal of expired authority, administrator replacement and full departure inventory are not qualified.",
        [
            "apps/api/impact_api/administration.py",
            "qualification/test_administration.py",
            "docs/RELEASE-0.2.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
            "apps/api/impact_api/contracts.py",
            "apps/api/impact_api/workspace_administration.py",
            "qualification/test_workspace_administration.py",
            "docs/RELEASE-0.15.md",
        ],
    ),
    (
        "FR-IAM-001",
        "Provisioned-identity invitations, membership changes, independent role approval, suspension and revocation are implemented: the inviter chooses tenant, role template, scopes, expiry and the intended verified identity; acceptance requires the nominated verified identity, a valid token and current inviter authority and creates one membership; resend invalidates the earlier link (qualification/test_administration.py). v0.16 adds email delivery of the invitation through the worker (apps/api/impact_api/delivery.py, worker.py; qualification/test_worker.py): creating or resending an invitation records one delivery intent in the same transaction holding no token and no clear address (the address is sealed, the link is re-derived from tenant, invitation and generation when sent); the worker sends the link only while that generation is current, so a resent, revoked, expired or closed invitation's earlier intent becomes SUPERSEDED and is never sent; each intent carries its own delivery state (SENT, retried with backoff, DEAD with an error class such as RECIPIENT_REFUSED or SMTP_PERMANENT_REJECTION), and sending the email creates no membership — acceptance is unchanged. Evidence is on a local SMTP sink and the synthetic sink only. Not covered: bulk invitation outcomes separating created, duplicate, invalid and delivery-failed rows (no bulk invitation exists), the seven-day default expiry as a qualified default, a live email provider with bounces, SPF/DKIM and sending limits, and federation assurance and recovery.",
        [
            "apps/api/impact_api/administration.py",
            "qualification/test_administration.py",
            "docs/RELEASE-0.2.md",
            "apps/api/impact_api/delivery.py",
            "apps/api/impact_api/worker.py",
            "qualification/test_worker.py",
            "docs/RELEASE-0.16.md",
        ],
    ),
    (
        "FR-TEN-003 FR-IAM-002 FR-IAM-006 FR-IAM-008 FR-IAM-013 FR-IAM-014 FR-ACC-003 FR-ACC-006 FR-ACC-012",
        "Provisioned-identity invitations, membership changes, independent role approval, suspension and revocation are implemented. Federation assurance, recovery, all identity providers and full departure inventory are not qualified.",
        [
            "apps/api/impact_api/administration.py",
            "qualification/test_administration.py",
            "docs/RELEASE-0.2.md",
        ],
    ),
    (
        "FR-ACC-001 FR-ACC-002 FR-ACC-004 FR-ACC-005 FR-ACC-011 FR-SEC-004 FR-SEC-012 FR-INT-004 FR-INT-005",
        "Implemented routes enforce explicit grants, tenant fences, natural-person independence, revisions and retry receipts. Native concurrency evidence is limited to the raced approvals, operation replays, close reviews and renewal-versus-revocation cases of qualification/test_native_concurrency.py (v0.14); every future module, audit tamper evidence and production assurance remain open.",
        [
            "apps/api/impact_api/store.py",
            "apps/api/impact_api/auth.py",
            "qualification/test_live_application.py",
        ],
    ),
    (
        "FR-SEC-003",
        "Implemented routes enforce explicit grants, tenant fences, natural-person independence, revisions and retry receipts. v0.14 adds native PostgreSQL evidence for the database side of the fence: the API runs on three separately provisioned login roles (impact_app_login, impact_identity_login, impact_platform_login; NOINHERIT, NOBYPASSRLS, exactly one privilege-role membership each) with IMPACT_REQUIRE_UNPRIVILEGED_DB=1, and qualification/test_native_roles.py proves under those real logins (PostgreSQL 16.13 locally, 17.11 in CI) that each login assumes only its own role, that impact_app reads nothing without a transaction-local tenant and exactly one tenant with one, that it cannot read the control-plane tables, that impact_identity reaches identity tables only, that impact_platform writes only its RESTRICTIVE object types, and that the runtime guard refuses superuser, BYPASSRLS, owner-member and shared logins on every transaction (PRIVILEGED_RUNTIME_CONNECTION, SHARED_RUNTIME_LOGIN) with no login name in any response. The restore drill re-verifies ownership, RLS, policies, grants and the fences on a restored copy. Not covered: attachments, asynchronous jobs, caches, search, AI and support paths (none exist), connection pooling and context reset on pooled connections, audit tamper evidence, an isolation fixture with synthetic tenant markers across every module, and production assurance.",
        [
            "apps/api/impact_api/store.py",
            "apps/api/impact_api/auth.py",
            "qualification/test_live_application.py",
            "scripts/provision_logins.py",
            "qualification/test_native_roles.py",
            "scripts/restore_drill.py",
            "docs/evidence/native-application-tests.xml",
            "docs/evidence/native-qualification.json",
            "docs/RELEASE-0.14.md",
        ],
    ),
    (
        "FR-PLN-006 FR-PRG-001 FR-PRG-005 FR-PRG-006 FR-PRG-007 FR-IND-001 FR-IND-002 FR-IND-005 FR-IND-007 FR-IND-008 FR-IND-009 FR-IND-010 FR-IND-012 FR-DQ-006",
        "Manual FLOW measures, independently approved definitions/plans, reviewed obligation exceptions, eligible assignments, reference selection and programme readiness are implemented. Historical expected, required and excepted counts are preserved. Rich planning, reference administration, automated schedules and the other measurement profiles remain open.",
        ["apps/api/impact_api/measurement.py", "qualification/test_work_center.py", "docs/RELEASE-0.7.md"],
    ),
    (
        "FR-CAL-001 FR-CAL-002 FR-CAL-003 FR-CAL-005 FR-CAL-008 FR-CAL-009 FR-CAL-010 FR-CAL-015 FR-DAT-008 FR-ANA-004",
        "Decimal SUM and pooled ratios, revision-bound lineage, explicit contributor coverage and stale-result flags are implemented. Hierarchy, stock, overlap, weighting, dimensions and production workload qualification are not implemented.",
        [
            "apps/api/impact_api/domain.py",
            "apps/api/impact_api/service.py",
            "qualification/test_measurement.py",
        ],
    ),
    (
        "FR-CAL-011 FR-DAT-009 FR-WFL-001 FR-WFL-002 FR-WFL-003 FR-WFL-004 FR-WFL-010",
        "Single-stage independent review and governed source/plan/assignment amendments are implemented. Affected provisional result revisions receive durable invalidations and personal recalculation work; current approved inputs produce a replacement revision while old lineage remains immutable. Cross-period aggregates, dashboards, reports, distributed artifacts, bulk amendments, configurable multistage policies and escalation remain open.",
        ["apps/api/impact_api/work.py", "qualification/test_work_center.py", "docs/RELEASE-0.7.md"],
    ),
    (
        "FR-WFL-006",
        "A personal work centre implements deduplicated recalculation assignments and safe in-app notices with event identity, acknowledgement and exact-retry protection. v0.16 adds per-recipient delivery status: every notice records an IN_APP delivery intent that the worker delivers exactly once (fenced SENT, one notification_delivery row and a consumer receipt in one transaction; the notice gains delivered_at beside acknowledged_at), a notice for a recipient who is no longer active is SUPERSEDED rather than delivered, and delegated-authority expiry reminders (14 and 3 days) are created once per principal, expiry instant and threshold however often the scan runs (qualification/test_worker.py). Due obligations, returned work, channel preferences, digests, email or push delivery of notices, muting rules for mandatory security notices, failed-delivery remediation flags and escalations remain open.",
        [
            "apps/api/impact_api/work.py",
            "apps/web/src/WorkCenter.tsx",
            "docs/RELEASE-0.7.md",
            "apps/api/impact_api/worker.py",
            "qualification/test_worker.py",
            "docs/RELEASE-0.16.md",
        ],
    ),
    (
        "FR-WFL-007 FR-WFL-008",
        "Programme-period close previews pin plans, sources and provisional results; independently reviewed exclusions remain visible but do not block required completion. Approval creates official results and an immutable versioned snapshot. Scoped, time-bounded restatement preserves and supersedes the original. Optional-late-source policy, distributed-artifact impact and multi-period downstream regeneration remain open.",
        [
            "apps/api/impact_api/period_governance.py",
            "qualification/test_period_governance.py",
            "docs/RELEASE-0.5.md",
        ],
    ),
    (
        "FR-RPT-003 FR-RPT-005 FR-RPT-007 FR-RPT-009 FR-RPT-010",
        "Internal reports bind to a locked snapshot, approved template and official result/evidence revisions. Independent approval records an append-only reconciliation digest. Numeric narrative claims must use known binding placeholders; deterministic semantic HTML and CSV artifacts are frozen for an independently reviewed, named-recipient, expiring disclosure and every view/download is logged. Withdrawal closes access without deleting artifacts or history. v0.23: worker-rendered PDF, XLSX and DOCX artifacts of the same frozen package (deterministic bytes, displayed values only, SHA-256 per artifact; qualification/test_report_exports.py::test_renderers_are_byte_deterministic_and_carry_only_displayed_values, test_pdf_refuses_glyphs_it_cannot_draw_instead_of_dropping_them, test_worker_renders_immutable_artifacts_whose_numbers_match_the_snapshot_and_html, test_transient_failures_back_off_then_fail_with_an_error_class_only) are delivered only through a reviewed disclosure that pins exact artifacts, with logged recipient downloads and withdrawal (test_published_exports_reach_named_recipients_only_and_withdrawal_blocks_them, test_export_request_needs_an_approved_package_the_capability_and_the_tenant). Charts, page-break/caveat validation, accessibility conformance, non-Latin PDF fonts, anonymous publication, scheduled delivery, supersession notices and distributed-artifact handling remain open. QA 2026-10 adds the export-browser check (tools/browser/export-check.mjs: request PDF, XLSX and DOCX in the UI, worker run, download with matching SHA-256, a disclosure pinning the PDF reaches the named partner while undisclosed formats and non-recipients get 404); browser evidence supports, it does not move, these requirements.",
        [
            "apps/api/impact_api/reporting.py",
            "qualification/test_reporting.py",
            "qualification/test_publication.py",
            "docs/RELEASE-0.6.md",
            "docs/RELEASE-0.8.md",
            "apps/api/impact_api/exports.py",
            "apps/api/impact_api/export_render.py",
            "qualification/test_report_exports.py",
            "docs/RELEASE-0.23.md",
            "tools/browser/export-check.mjs",
            "docs/evidence/export-browser-tests.json",
        ],
    ),
    (
        "FR-RPT-004 FR-UX-001 FR-UX-002 FR-UX-003 FR-UX-004 FR-UX-005 FR-UX-009",
        "Browser workspaces, labelled dialogs, bound narrative authoring, controlled-publication actions, explicit status and health endpoints are implemented. QA 2026-10 adds automated WCAG A/AA scans of every workspace area (tools/browser/a11y-check.mjs, group a11y-browser: 43 page states, 0 serious or critical violations, no accepted exceptions), visible focus with 3:1 outline contrast, dialog focus return, keyboard-operable tab lists, a skip link and status announcements for saves, export states and evidence notices. Screen-reader review, drag alternatives (no drag exists), the invalid-field and stale-revision acceptance, full accessibility/usability qualification, anonymous publication, service monitoring and all remaining screens are open.",
        [
            "apps/web/src/main.tsx",
            "tools/browser/reporting-check.mjs",
            "docs/IMPLEMENTATION.md",
            "apps/web/src/a11y.ts",
            "tools/browser/a11y-check.mjs",
            "docs/evidence/a11y-browser-tests.json",
            "docs/current/ACCESSIBILITY-STATEMENT.md",
            "docs/QA-A11Y-2026-10.md",
        ],
    ),
    (
        "FR-OPS-005",
        "Browser workspaces, labelled dialogs, bound narrative authoring, controlled-publication actions, explicit status and health endpoints are implemented. v0.14 adds to the health surface: with unprivileged connections required, /health/ready first verifies that the app, identity and platform connections are three distinct unprivileged logins and answers 503 with a reason code only (PRIVILEGED_RUNTIME_CONNECTION, SHARED_RUNTIME_LOGIN, PLATFORM_NOT_CONFIGURED; no login name reaches a response), the same check refuses every transaction, and the native restart check shows readiness and the runtime manifest unchanged across an API restart. Service monitoring proper remains open: no health view separated by component, no journey success, latency, backlog, freshness or quota measurement, no incident record, no tenant-cohort view, no metrics, log pipeline or alerting exists; full accessibility/usability qualification, anonymous publication and all remaining screens are also open. Operations hardening (October 2026) adds the operator-only GET /v1/platform/metrics (platform API 1.6.0; apps/api/impact_api/ops_metrics.py): request counts by route family and status class with a latency histogram, worker freshness, DEAD and held deliveries, unsent deliveries and unfinished jobs, tenants by state and object-store space, no path, tenant data or identity (qualification/test_ops_metrics.py::test_operators_read_counts_and_no_tenant_data, test_metrics_are_for_platform_operators_only; test_ops_unit.py::test_request_metrics_count_families_classes_and_latency_without_paths), and a five-minute alert check into deploy-status.json (deploy/ops-check.sh, deploy/ops_alerts.py). Still open: journey success by tenant cohort, connector and AI separation, incident linkage, metric history and any notification channel.",
        [
            "apps/web/src/main.tsx",
            "tools/browser/reporting-check.mjs",
            "docs/IMPLEMENTATION.md",
            "apps/api/impact_api/main.py",
            "apps/api/impact_api/store.py",
            "qualification/test_native_roles.py",
            "qualification/test_native_restart.py",
            "docs/evidence/native-qualification.json",
            "docs/RELEASE-0.14.md",
            "apps/api/impact_api/ops_metrics.py",
            "apps/api/impact_api/metrics_contracts.py",
            "qualification/test_ops_metrics.py",
            "qualification/test_ops_unit.py",
            "deploy/ops_alerts.py",
            "docs/RELEASE-OPS-2026-10.md",
        ],
    ),
    (
        "VF-DIN-002",
        "Native PostgreSQL only (qualification/test_native_concurrency.py, 11 cases, executed on PostgreSQL 16.13 in the workspace on 29 September 2026 and 17.11 in CI; skipped on PGlite, whose single process lock cannot contend): two independent reviewers approving one candidate revision at once admit exactly one decision (200 and CONFLICT_VERSION; one new revision each of candidate and workflow, one audit event, one outbox event, one receipt); the same command from two threads returns the one receipt and writes one revision; the same operation identifier with different payloads admits exactly one (CONFLICT_OPERATION for the other); two independent close reviews of one period produce one OFFICIAL snapshot version and PERIOD_ALREADY_SNAPSHOTTED for the other; a renewal approval raced with a pinned-grant revocation in both orders yields either the renewed set with the stale revocation refused (CONFLICT_VERSION) or the revoked grant with the approval refused (AUTHORITY_CHANGED), never both; ten reads complete beside a held tenant advisory lock while a write queues, and a write held past lock_timeout is refused with no receipt. Not covered: two concurrent edits of one record, repeated import commands and interrupted bulk jobs (no import or bulk job exists), the LLD lock order across objects under concurrent writers (the mixed-write case is a no-regression smoke test), connection pooling, and any load profile. The target's recoverable explicit partial outcomes exist only where an operation defines them.",
        [
            "qualification/test_native_concurrency.py",
            "apps/api/impact_api/service.py",
            "apps/api/impact_api/store.py",
            "docs/evidence/native-application-tests.xml",
            "docs/evidence/native-qualification.json",
            "docs/RELEASE-0.14.md",
        ],
    ),
    (
        "VF-DR-003",
        "A scripted, verified restore exists and has been executed (scripts/restore_drill.py; 29 September 2026 on PostgreSQL 16.13, and in the CI native job on 17.11 for commit c759e9e): pg_dump -Fc of the qualification database (3,427,234 bytes in 0.45 s), pg_restore into a sibling database (1.56 s), a migrator checksum pass that applies nothing and verifies all 16 ledgered checksums, the seeded OFFICIAL 46.36 present in its snapshot revision with its payload hash, equal row counts in all 151 impact tables (30,016 rows), identical ownership, RLS flags, policies, functions and grants, the tenant fences and control-plane denials intact for impact_app, and no credential altered. This is a CI-scale restore drill of a disposable qualification database, not a backup regime: no scheduled backup, retention window, off-site or immutable copy, protection against alteration or credential compromise, monthly restore cadence, quarterly disaster exercise, key recovery, attachment integrity (no attachments exist) or deletion/restriction replay before reopening exists, and no RPO or RTO is established. A restore of a production-scale database is not qualified. Operations hardening (October 2026) adds, on the staging server, nightly verified backup sets (both databases, roles without passwords, the evidence object volume as a tar, SHA-256 manifest; written in a hidden directory, verified with pg_restore --list, a full tar read and sha256sum, then renamed; 7 daily and 4 weekly within the 35-day default; a disk guard) and a weekly on-server restore drill into throwaway containers that checks object digests against their names, blob rows against objects, a migrator checksum pass, ownership, forced fences and the identity-provider realm and records duration and backup age (deploy/backup.sh, deploy/restore-drill.sh, deploy/drill_restore.sh, deploy/restore_check.py; qualification/test_ops_unit.py::test_backup_set_holds_databases_roles_objects_and_a_verified_manifest, test_sundays_set_is_kept_weekly_by_hard_link_and_retention_prunes_oldest, test_verification_catches_a_changed_file, test_drill_restores_the_newest_set_and_skips_the_bootstrap_superuser, test_object_digests_match_names_and_blob_rows_find_their_objects, test_drill_record_measures_duration_and_backup_age; the CI container-stack job restores a set and runs the drill). Still open: protection against alteration and credential compromise (sets live on the same server and root account), an off-server copy, the quarterly disaster exercise, key recovery and deletion replay before reopening (TH27); no RPO or RTO target is met.",
        [
            "scripts/restore_drill.py",
            "docs/evidence/native-restore-drill.json",
            "docs/evidence/native-qualification.json",
            "docs/RELEASE-0.14.md",
            "docs/current/OPERATIONS-GUIDE.md",
            "deploy/backup.sh",
            "deploy/restore-drill.sh",
            "deploy/drill_restore.sh",
            "deploy/restore_check.py",
            "qualification/test_ops_unit.py",
            "docs/current/DEPLOYMENT-GUIDE.md",
            "docs/RELEASE-OPS-2026-10.md",
        ],
    ),
    (
        "FR-TEN-002 FR-TEN-010 FR-IAM-003 FR-IAM-006 FR-IAM-008 FR-IAM-010 FR-IAM-013 FR-ACC-002",
        "v0.9 adds versioned custom roles, independently reviewed flat group access, immediate organisation moves with cycle checks, renewal without old-access resurrection, nominated custody transfer, self-service session revocation/preferences and configured ACR enforcement. v0.13 adds reviewed renewal/extension of unexpired delegated authority (owner proposal pinning the exact current ceilings, second-administrator acceptance, independent operator approval, database-owned re-dating of only the pinned rows); expired authority is not renewable and single-administrator tenants are unsupported. Further onboarding acceptance, provider MFA/recovery qualification, action-bound step-up, future-effective organisation impact and full access certification remain open.",
        [
            "apps/api/impact_api/workspace_administration.py",
            "apps/api/impact_api/account.py",
            "qualification/test_workspace_administration.py",
            "tools/browser/workspace-check.mjs",
            "docs/RELEASE-0.9.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
        ],
    ),
    (
        "FR-IAM-002",
        "Provisioned-identity invitations, membership changes, independent role approval, suspension and revocation are implemented. v0.15 qualifies the login binding against a live provider (Keycloak 26.7.4, development mode, in-memory database, qualification/test_live_idp.py: 16 cases on PGlite and 16 on native PostgreSQL 16.13 login roles, 29 September 2026): sign-in binds the provider issuer and stable subject to the fixture identity (the fixture's auth_identity rows are re-pointed to the realm issuer by subject); tokens of another issuer (a second realm of the same provider with the same client and an author user), a tampered signature, a key outside the provider JWKS, an expired token, an ID token presented as a bearer credential (typ check) and provider role claims are refused or confer nothing; a disabled provider account cannot sign in; missing assurance fails safely (a password-only session is refused every fresh-assurance operation). Not covered: an administrator-facing provider configuration, tenant binding and designated-account test mode, certificate or key expiry display and overlapping rotation, provider interruption, emergency local recovery, SAML or any provider other than one Keycloak realm, and a managed or customer-provided provider.",
        [
            "apps/api/impact_api/administration.py",
            "qualification/test_administration.py",
            "docs/RELEASE-0.2.md",
            "apps/api/impact_api/auth.py",
            "scripts/idp.py",
            "tools/idp/qualification-realm.json",
            "qualification/test_live_idp.py",
            "docs/evidence/idp-tests.xml",
            "docs/evidence/idp-native-tests.xml",
            "docs/evidence/idp-qualification.json",
            "docs/RELEASE-0.15.md",
        ],
    ),
    (
        "FR-IAM-003",
        "v0.9 adds versioned custom roles, independently reviewed flat group access, immediate organisation moves with cycle checks, renewal without old-access resurrection, nominated custody transfer, self-service session revocation/preferences and configured ACR enforcement. v0.13 adds reviewed renewal/extension of unexpired delegated authority (owner proposal pinning the exact current ceilings, second-administrator acceptance, independent operator approval, database-owned re-dating of only the pinned rows); expired authority is not renewable and single-administrator tenants are unsupported. v0.15 exercises step-up against a live provider: the qualification realm's browser flow is level 1 password and level 2 TOTP with an ACR map, the platform requests urn:impact:acr:mfa with max_age=0, a session at the password level reads normally but is refused every tenant and account fresh-assurance operation, a user without a second factor is sent to TOTP enrolment before any code is issued, and after TOTP a fresh-assurance operation succeeds until 300 s after the provider's own auth_time (FRESH_AUTHENTICATION_REQUIRED at 301 s, emulated by moving the recorded auth_time back) in qualification/test_live_idp.py and the idp-browser check. Not covered: completion of enrolment, passkeys, a challenge bound to the intended action (step-up is per session, not per pending action), blocking removal of the last qualifying factor, SMS exclusion, authenticator synchronisation disclosure and provider-side recovery.",
        [
            "apps/api/impact_api/workspace_administration.py",
            "apps/api/impact_api/account.py",
            "qualification/test_workspace_administration.py",
            "tools/browser/workspace-check.mjs",
            "docs/RELEASE-0.9.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
            "apps/api/impact_api/auth.py",
            "scripts/idp.py",
            "tools/idp/qualification-realm.json",
            "qualification/test_live_idp.py",
            "docs/evidence/idp-tests.xml",
            "docs/evidence/idp-native-tests.xml",
            "docs/evidence/idp-qualification.json",
            "docs/RELEASE-0.15.md",
            "tools/browser/idp-check.mjs",
            "docs/evidence/idp-browser-tests.json",
        ],
    ),
    (
        "FR-IAM-006",
        "v0.9 adds versioned custom roles, independently reviewed flat group access, immediate organisation moves with cycle checks, renewal without old-access resurrection, nominated custody transfer, self-service session revocation/preferences and configured ACR enforcement. v0.13 adds reviewed renewal/extension of unexpired delegated authority (owner proposal pinning the exact current ceilings, second-administrator acceptance, independent operator approval, database-owned re-dating of only the pinned rows); expired authority is not renewable and single-administrator tenants are unsupported. v0.15 adds live-provider logout (qualification/test_live_idp.py, qualification/test_backchannel_logout.py, idp-browser check): POST /auth/logout revokes the server session at once (the old cookie then gets 401) and returns the provider end-session URL with a sealed id_token_hint, after which the provider session is gone (prompt=none returns login_required); a logout after idle or absolute timeout still clears the cookie; a verified back-channel logout token revokes exactly the platform sessions of that provider session and a replayed token is refused. Server authority is therefore invalidated independently of what the browser still shows. Not covered: clearing in-memory client state and cached navigation, browser back and a queued export from a revoked session (no export job exists), shared-device mode, the idle warning that preserves drafts, and bearer access tokens, which remain valid until exp (120 s in the realm) after a provider logout.",
        [
            "apps/api/impact_api/workspace_administration.py",
            "apps/api/impact_api/account.py",
            "qualification/test_workspace_administration.py",
            "tools/browser/workspace-check.mjs",
            "docs/RELEASE-0.9.md",
            "apps/api/impact_api/authority_renewal.py",
            "qualification/test_authority_renewal.py",
            "tools/browser/renewal-check.mjs",
            "docs/RELEASE-0.13.md",
            "apps/api/impact_api/auth.py",
            "scripts/idp.py",
            "tools/idp/qualification-realm.json",
            "qualification/test_live_idp.py",
            "docs/evidence/idp-tests.xml",
            "docs/evidence/idp-native-tests.xml",
            "docs/evidence/idp-qualification.json",
            "docs/RELEASE-0.15.md",
            "qualification/test_backchannel_logout.py",
            "tools/browser/idp-check.mjs",
            "docs/evidence/idp-browser-tests.json",
        ],
    ),
    (
        "FR-PLN-001",
        "v0.18 implements typed framework nodes (IMPACT, OUTCOME, OUTPUT, ACTIVITY) with stable node identities, title, description, owner and indicator placement in one governed framework per programme, edited in a table with a hierarchy tree (apps/web/src/Planning.tsx). Validation exercised by executed tests (qualification/test_planning.py::test_hierarchy_structure_is_refused, test_unmeasured_output_blocks_submission_until_documented_exception, test_planning_unit.py::test_structure_rules): containment cycles, including a node containing itself, orphaned parent references and deletion of a node that places indicators in the approved baseline (NODE_REFERENCED) are rejected on every save, as are level inversions and indicators placed twice or from another programme; renaming an output in a draft keeps its node identity and indicator placement (test_framework_draft_review_baseline_and_child_version). Not covered: a relationship (graph) view editing the same identities, relationship links and numeric aggregation links as distinct objects (theory-of-change relationships are accepted only empty and assumption or input nodes are refused), activity-to-output links beyond containment, and the graph half of the acceptance scenario.",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "apps/web/src/Planning.tsx",
            "tools/browser/planning-check.mjs",
            "docs/evidence/native-application-tests.xml",
            "docs/evidence/planning-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
        ],
    ),
    (
        "FR-PLN-003",
        "v0.18 submits a framework with its completeness report, shows the reviewer the candidate with that report and, for a child draft, the superseded revision and a comparison (nodes added, removed, changed); approval by an independent natural person freezes a baseline version in the insert-only framework_baseline register, and a later change is a child draft with an effective date that supersedes exactly one approved revision (test_framework_draft_review_baseline_and_child_version, test_second_framework_child_is_refused_after_the_first_is_approved, test_native_planning_registers_are_fenced_and_insert_only). Validation exercised: a period close pins the governing framework revision (the latest baseline effective before the period ends) into the snapshot, and a later approved revision does not re-place the locked period (test_close_pins_governing_framework_revision); the first baseline keeps its approved wording after a July revision. Not covered: the review listing impacted targets, activities, templates and obligations; regeneration of an earlier report against its original hierarchy and language (reports do not bind a framework); deletion of an obsolete draft (no delete operation exists).",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "apps/api/impact_api/period_governance.py",
            "docs/evidence/native-application-tests.xml",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
        ],
    ),
    (
        "FR-PLN-010",
        "v0.18 implements a completeness view listing orphan nodes, unmeasured impact/outcome/output nodes, missing owners and incomplete nodes, and programme indicators not placed on any node, each with severity, rule, object and assigned resolver. Validation and acceptance exercised (test_unmeasured_output_blocks_submission_until_documented_exception, test_exception_authorship_and_review_date): structural invalidity is refused on save and can never be excepted, an exception that matches no current warning becomes an error, submission of a framework with an unmeasured output stays blocked (FRAMEWORK_INCOMPLETE) with an assigned resolver until a documented exception with a reason and a review date not in the past is recorded, the server stamps who recorded it, and the accepted exceptions remain visible in the approved baseline revision; the independent approver of that revision is recorded in the register. Not covered: invalid sources, unreviewed assumptions and conflicting reporting obligations (no such checks), unsupported official arithmetic as a completeness rule, and acceptance by a separately named authority per exception (the approver of the revision is the authority; no per-exception acceptance record exists).",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "tools/browser/planning-check.mjs",
            "docs/evidence/planning-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
        ],
    ),
    (
        "FR-IND-003",
        "v0.18 implements targets and baselines per indicator instance and programme period with target kind (VALUE, RANGE, MILESTONE), value and explicit value state, direction (higher, lower, within range, milestone), basis (original, baseline, revised) and the pinned approved definition revision (its unit); revised targets and baseline corrections supersede the approved revision with a reason, and targets versus actuals shows the selected target's basis and binding version. Validation and acceptance exercised (test_planning_unit.py::test_higher_target_attainment_is_uncapped, test_lower_target_reports_signed_deviation_without_inverting_success, test_zero_target_and_zero_baseline_are_undefined_not_divided; test_planning.py::test_targets_baselines_milestones_and_provisional_progress): actual 120 against a higher target of 100 is 120.00 percent attainment, uncapped; a lower target of 10 with actual 8 is ACHIEVED with deviation -2; a zero target gives Undefined attainment (ZERO_TARGET) rather than a division, and milestones need an assessment. Not covered: a reviewed difference logic for zero targets, status thresholds, disaggregated and cumulative targets, measurement dates other than a programme period, and restated comparisons after close (FR-IND-004).",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "apps/web/src/Planning.tsx",
            "tools/browser/planning-check.mjs",
            "docs/evidence/planning-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
        ],
    ),
    (
        "FR-ANA-003",
        "v0.18 implements one comparison view, the targets-versus-actuals table (GET /programmes/{id}/targets-vs-actuals and the Targets vs actuals tab), binding the actual, the baseline and the selected target revision with its direction, basis (original or revised), binding version and period; the actual's source is shown (OFFICIAL only from the programme's own locked snapshot, PROVISIONAL from its own calculations) and overachievement stays visible. Validation and acceptance exercised (test_planning_unit.py::test_zero_target_and_zero_baseline_are_undefined_not_divided, test_negative_baseline_has_no_percentage_change, test_lower_target_reports_signed_deviation_without_inverting_success; test_planning.py::test_targets_baselines_milestones_and_provisional_progress, test_period_close_pins_targets_and_uses_official_result): a zero or negative baseline gives an Undefined percentage change (NON_POSITIVE_BASELINE), never an infinite trend, and a lower-is-better target of 10 with actual 8 shows ACHIEVED and the declared deviation without inverting success. v0.24 adds the dashboard comparison: the target pinned by the snapshot, status against the official value naming which value it compared (compared_with), a zero-baseline axis in the trend chart and an Undefined status for a zero target or an UNDEFINED result (test_dashboards.py::test_official_pooled_ratio_from_the_programme_snapshot, test_undefined_result_is_never_zero). Not covered: widgets and configurable axis scales, cumulative curves (no cumulative target exists, so the cumulative-to-flow conversion rule is untested), revised-target labelling on charts beyond the basis text, and time semantics beyond one period.",
        [
            "apps/api/impact_api/planning.py",
            "apps/api/impact_api/planning_contracts.py",
            "qualification/test_planning.py",
            "qualification/test_planning_unit.py",
            "apps/web/src/Planning.tsx",
            "tools/browser/planning-check.mjs",
            "docs/evidence/planning-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/RELEASE-0.18.md",
            "apps/api/impact_api/dashboards.py",
            "apps/api/impact_api/dashboard_contracts.py",
            "qualification/test_dashboards.py",
            "apps/web/src/Dashboards.tsx",
            "tools/browser/dashboard-check.mjs",
            "docs/evidence/dashboard-browser-tests.json",
            "docs/RELEASE-0.24.md",
        ],
    ),
    (
        "VF-DIN-001",
        "v0.19 adds a versioned golden corpus (qualification/golden/calculation-corpus-v1.json, corpus 1.1.0, 40 hand-prepared vectors covering CAL01, CAL02, CAL05, CAL06, CAL07, CAL09, CAL16 and CAL20 plus rounding boundaries, magnitude, missingness, invalid input and dimensions) and a reconciliation harness (qualification/test_golden.py, make golden) that compares an independent exact-rational reference with the hand-prepared values, then the domain code and the live API path with the reference, on raw stored and displayed decimals per total and per category; every executed vector passes (docs/evidence/golden-reconciliation.json). Not covered: CAL03, CAL04, CAL10-CAL15, CAL17-CAL19 (overlap, hierarchy, conversions, targets, weighting, currency, cost and disclosure are not implemented or not in the corpus), correction, version and permission variants of each vector, and report bindings.",
        [
            "apps/api/impact_api/domain.py",
            "apps/api/impact_api/calculation_contracts.py",
            "apps/api/impact_api/service.py",
            "qualification/test_calculation_methods.py",
            "qualification/test_golden.py",
            "qualification/golden/calculation-corpus-v1.json",
            "docs/evidence/golden-reconciliation.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.19.md",
        ],
    ),
    (
        "FR-IND-006",
        "v0.19 lets an indicator definition pin a versioned disaggregation scheme (up to five dimensions with code, label, version, multiselect and exhaustive flags and declared category codes; UNSPECIFIED reserved) and observations carry codes checked against it at draft, submission, amendment and calculation; results carry per-category values computed from source rows. Validation and acceptance exercised (test_calculation_methods.py::test_multiselect_categories_are_nonadditive_and_unique_total_stays_one, test_observation_codes_must_match_the_pinned_scheme, test_category_correction_through_change_request; corpus FT-IND-006-multiselect): one contribution with two selected categories counts in both, the total stays one and the categories are labelled NONADDITIVE. Not covered: applicability rules, explicit missing/unknown/declined codes beyond what a scheme declares, reviewed crosswalks for a changed scheme (FR-CAL-007), unique-participant totals (no participants exist), and dimension version validation (free text).",
        [
            "apps/api/impact_api/domain.py",
            "apps/api/impact_api/calculation_contracts.py",
            "apps/api/impact_api/service.py",
            "qualification/test_calculation_methods.py",
            "qualification/test_golden.py",
            "qualification/golden/calculation-corpus-v1.json",
            "docs/evidence/golden-reconciliation.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.19.md",
        ],
    ),
    (
        "FR-FRM-001",
        "v0.20 adds a form builder whose fields live inside the governed Form revision: stable field_id and code, position, type (TEXT, DECIMAL, INTEGER, BOOLEAN, SINGLE_CHOICE), label, help, required, numeric bounds, text length, choices, and an optional indicator binding with value role or a disaggregation dimension; submitting for review locks the exact revision and starts the independent approval, and publication is a separate fresh-assurance action into the insert-only form_publication register. Validation text exercised (test_forms.py::test_form_definition_validation, test_exhaustive_dimension_field_must_be_answered_with_the_value, test_numerator_and_denominator_answers_pool_into_a_percentage, test_form_review_requires_independence_and_publish_requires_approval; forms-browser design step): unsupported combinations (choices on a non-choice field, bounds on a text field, inverted bounds, duplicate codes, a binding on a text field or to a non-manual or foreign indicator, a ratio without both components, an undeclared or multiselect dimension, an optional or differently relevant exhaustive-dimension field) are rejected before publishing. Not covered: groups and repeat groups (100 repeat entries, two nesting levels), field classification, preview in desktop and mobile modes, calculated fields, photos and the 200-question load qualification (the contract caps 200 fields; no test at that size); FT-FRM-001 (household members, photo, calculated age) is not executable.",
        [
            "apps/api/impact_api/forms.py",
            "apps/api/impact_api/forms_contracts.py",
            "apps/web/src/Forms.tsx",
            "infrastructure/migrations/0021_web_forms.sql",
            "qualification/test_forms.py",
            "tools/browser/forms-check.mjs",
            "docs/evidence/forms-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.20.md",
        ],
    ),
    (
        "FR-FRM-002",
        "v0.20 implements one bounded relevance rule per field (relevant_when: an earlier yes/no or choice field equals a declared code), typed by reference to an earlier field and a declared code so that cycles and forward or undeclared references are refused (FORM_RELEVANCE_INVALID); the server evaluates the same versioned rules in field order and the web client uses the same rule to show or hide a question. Validation text exercised (test_forms.py::test_submission_refuses_incomplete_and_hidden_answers, test_draft_answers_are_validated_against_the_version, test_form_definition_validation, test_blank_answers_keep_explicit_value_states; forms-browser fill-in step): a tampered payload carrying an answer to a hidden field is refused (ANSWER_NOT_RELEVANT), a relevant required answer cannot be omitted, a hidden bound field becomes NOT_APPLICABLE. Not covered: a bounded expression catalogue beyond equality, required rules separate from relevance, the visible confirmation and declared policy for clearing newly irrelevant values (the client hides them and the server refuses them), explicitly retained hidden values, and references to inaccessible fields (fields have no classification).",
        [
            "apps/api/impact_api/forms.py",
            "apps/api/impact_api/forms_contracts.py",
            "apps/web/src/Forms.tsx",
            "infrastructure/migrations/0021_web_forms.sql",
            "qualification/test_forms.py",
            "tools/browser/forms-check.mjs",
            "docs/evidence/forms-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.20.md",
        ],
    ),
    (
        "FR-FRM-003",
        "v0.20 moves a form through draft, independent review and publication (no isolated test stage); each publication appends a version to the insert-only form_publication register pinning the approved revision, and a submission retains the exact published form revision it was captured on (form_version required at creation and immutable). Validation and acceptance exercised (test_forms.py::test_superseded_version_quarantines_rather_than_inventing_answers, test_form_version_review_publication_and_submission_to_calculation, test_submission_draft_requires_a_form_version, test_native_form_publication_register_is_fenced_and_insert_only): after a new version with a new mandatory question is published, a response captured on the earlier version is preserved unchanged and quarantined (FORM_VERSION_SUPERSEDED) with no observations rather than completed or mapped. Not covered: compatibility declarations and acceptance cutoffs (only LOCK_PUBLISHED, so every older version is quarantined), reviewed mapping of quarantined responses, translation versions, revocation of an unsafe form, isolated test, and the offline-package scenario of FT-FRM-003 (no offline collection exists).",
        [
            "apps/api/impact_api/forms.py",
            "apps/api/impact_api/forms_contracts.py",
            "apps/web/src/Forms.tsx",
            "infrastructure/migrations/0021_web_forms.sql",
            "qualification/test_forms.py",
            "tools/browser/forms-check.mjs",
            "docs/evidence/forms-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.20.md",
        ],
    ),
    (
        "FR-FRM-006",
        "v0.20 saves server drafts of a response and resumes them with the same submission identity and pinned form version; submit validates the response against that version and returns a receipt, turning each bound indicator into a FORM-namespace observation submitted into the existing independent review in the same transaction. Validation text exercised (forms-browser fill-in step: the submit response is dropped and the retry with the same operation identifier resolves to the original receipt and one submission; test_forms.py::test_form_and_submission_access_boundaries for stale revisions and server-owned fields, test_response_drafters_are_authors_of_its_observations, test_bound_form_submit_requires_observation_submit). Not covered: local (browser) drafts and the indication of where a draft was saved beyond the server confirmation, the unsaved-changes warning, confirmation of intended finality as a separate step, a confirmation-pending state distinct from a retry, and returned work starting a linked correction revision (the FORM namespace is reserved and no submission correction exists).",
        [
            "apps/api/impact_api/forms.py",
            "apps/api/impact_api/forms_contracts.py",
            "apps/web/src/Forms.tsx",
            "infrastructure/migrations/0021_web_forms.sql",
            "qualification/test_forms.py",
            "tools/browser/forms-check.mjs",
            "docs/evidence/forms-browser-tests.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.20.md",
        ],
    ),
    (
        "FR-CAL-001 FR-CAL-003 FR-CAL-005 FR-CAL-008 FR-CAL-009 FR-CAL-010",
        "Decimal calculation with a bounded method catalogue (v0.19): SUM and POOLED_RATIO for FLOW, COUNT for EVENT, LAST_VALID for STOCK and CUMULATIVE (latest approved position; a tie with different values and a cumulative decline give UNDEFINED), labelled unweighted MEAN, MEDIAN, MIN and MAX; methods bound to measurement types and time semantics and refused at definition submission otherwise; 100-digit arithmetic, stored value half-up at 12 places and display derived from the stored value; absent value states never zero; revision-bound lineage, coverage and stale flags as before. Exercised by the golden corpus through reference, domain and live API (CAL01 51/110 = 46.36, CAL02 labelled 30, CAL05 end 20 not 45, CAL06 zero denominator UNDEFINED, CAL07 60.00 coverage, CAL09 1.005 to 1.01, CAL20 boundary) and test_calculation_methods.py. Not covered: cumulative increments (no verified baseline), maximum stock age, hierarchy, overlap, unit conversion, weighting and production workload qualification.",
        [
            "apps/api/impact_api/domain.py",
            "apps/api/impact_api/calculation_contracts.py",
            "apps/api/impact_api/service.py",
            "qualification/test_calculation_methods.py",
            "qualification/test_golden.py",
            "qualification/golden/calculation-corpus-v1.json",
            "docs/evidence/golden-reconciliation.json",
            "docs/evidence/application-tests.xml",
            "docs/evidence/native-application-tests.xml",
            "docs/RELEASE-0.19.md",
        ],
    ),
    (
        "FR-DAT-001",
        "v0.21 ingests a bounded tabular file carried in the import batch (CSV text or the first worksheet of an XLSX read with the standard library; at most 192 KiB of content, 500 rows and 500 observations): every cell is read as text, so leading zeros (00123), a 20-digit identifier and a quoted comma are kept exactly and shown raw beside their interpretation; dates are never guessed (03/04/2026 without a declared pattern is EVENT_AT_INVALID, read exactly with DD/MM/YYYY); a formula in a mapped column is quarantined; an unreadable archive or an XML DOCTYPE is refused before parsing (qualification/test_import.py::test_csv_import_preview_commit_review_and_receipts, test_quarantine_duplicates_and_atomic_mode, test_dimension_column_and_xlsx_source). Not covered: encoding, delimiter, sheet and header-row choice, locale-aware numbers, a formula mode other than reject, upload sessions and worker execution for larger files.",
        [
            "apps/api/impact_api/imports.py",
            "apps/api/impact_api/import_contracts.py",
            "infrastructure/migrations/0022_import_quality.sql",
            "qualification/test_import.py",
            "apps/web/src/Imports.tsx",
            "docs/RELEASE-0.21.md",
            "tools/browser/import-check.mjs",
            "docs/evidence/import-browser-tests.json",
        ],
    ),
    (
        "FR-DAT-002",
        "v0.21 maps source columns by header name to active manual indicator instances with role (VALUE, NUMERATOR, DENOMINATOR), stated unit, bounds, dimension columns and declared missing-value tokens, and previews every row before anything is written; a renamed or missing mapped column refuses the whole batch (MAPPING_COLUMN_MISSING) rather than shifting values, unit and role mismatches are refused, dropped columns are listed and an edit discards the staged preview (test_import.py::test_ratio_components_dimensions_and_mapping_refusals, test_csv_import_preview_commit_review_and_receipts, test_quarantine_duplicates_and_atomic_mode). Not covered: versioned, independently reviewed mapping objects (the mapping lives in the batch), transformations and AI-suggested mappings.",
        [
            "apps/api/impact_api/imports.py",
            "apps/api/impact_api/import_contracts.py",
            "infrastructure/migrations/0022_import_quality.sql",
            "qualification/test_import.py",
            "apps/web/src/Imports.tsx",
            "docs/RELEASE-0.21.md",
            "tools/browser/import-check.mjs",
            "docs/evidence/import-browser-tests.json",
        ],
    ),
    (
        "FR-DAT-004",
        "v0.21 classifies every staged row ACCEPTED, QUARANTINED with reason codes or DUPLICATE with reconciled counts; an atomic batch commits nothing when any row is not accepted, a partial batch commits exactly its accepted rows, and commit recomputes the staged outcome under the tenant lock and refuses a stale or mismatched preview hash; accepted rows become IMPORT-namespace observations submitted into the existing independent review in the same transaction (test_import.py::test_quarantine_duplicates_and_atomic_mode, test_commit_refuses_a_stale_preview, test_access_tenancy_independence_and_reserved_namespace). Not covered: the accepted-update versus unchanged-duplicate distinction, rejected versus quarantined outcomes, keyed update and controlled replacement (FR-DAT-003), and retrying corrected rows as a linked batch.",
        [
            "apps/api/impact_api/imports.py",
            "apps/api/impact_api/import_contracts.py",
            "infrastructure/migrations/0022_import_quality.sql",
            "qualification/test_import.py",
            "apps/web/src/Imports.tsx",
            "docs/RELEASE-0.21.md",
            "tools/browser/import-check.mjs",
            "docs/evidence/import-browser-tests.json",
        ],
    ),
    (
        "FR-DQ-003",
        "v0.21 detects exact duplicates on declared business keys: the same unit twice in one batch (DUPLICATE_IN_BATCH), the same unit, indicator and period already committed by an import, backed by the insert-only import_unit_register (DUPLICATE_UNIT_PERIOD), a form observation for the same unit and indicator in the period (DUPLICATE_SOURCE_KEY), and a duplicate arising between preview and commit (PREVIEW_STALE) (test_import.py::test_quarantine_duplicates_and_atomic_mode, test_commit_refuses_a_stale_preview; the register's fence and insert-only grants natively in test_native_import_unit_register_is_fenced_and_insert_only). Not covered: fuzzy matching, a review decision on a suspected duplicate, merge and unmerge, and comparison with manual observations.",
        [
            "apps/api/impact_api/imports.py",
            "apps/api/impact_api/import_contracts.py",
            "infrastructure/migrations/0022_import_quality.sql",
            "qualification/test_import.py",
            "apps/web/src/Imports.tsx",
            "docs/RELEASE-0.21.md",
            "tools/browser/import-check.mjs",
            "docs/evidence/import-browser-tests.json",
        ],
    ),
    (
        "FR-DQ-007",
        "v0.21 flags anomalies as warnings only: a modified z-score (threshold 3.5) against the indicator's 200 most recent approved PRESENT values, evaluated only with at least five values and a non-zero MAD; method, version and evaluated indicators are recorded on the batch, a flagged batch commits only with an explicit acceptance recorded on the batch, and the value is never changed or blocked (test_import.py::test_anomaly_warns_without_blocking). Not covered: suggested-state findings with an owner, confirm/dismiss/defer decisions and feedback, seasonality and period awareness.",
        [
            "apps/api/impact_api/imports.py",
            "apps/api/impact_api/import_contracts.py",
            "infrastructure/migrations/0022_import_quality.sql",
            "qualification/test_import.py",
            "apps/web/src/Imports.tsx",
            "docs/RELEASE-0.21.md",
            "tools/browser/import-check.mjs",
            "docs/evidence/import-browser-tests.json",
        ],
    ),
    (
        "FR-EVD-001",
        "v0.22 stores evidence files in a private, content-addressed object store that is never served directly, backs evidence draft revisions by a CLEAN upload or an https reference with server-owned file name, type, size and digest, records citations of exact evidence revisions from observation and calculated-result revisions in the insert-only evidence_attachment register, and serves content only through a mediated, re-authorised, audited download (qualification/test_evidence.py::test_upload_scan_evidence_version_citation_and_mediated_download exercises FT-EVD-001: version 1 is attached to an observation, version 2 is uploaded, and the observation still cites and serves version 1; test_attach_to_calculated_result_and_attachment_rules; test_access_is_capability_owner_and_tenant_bound; the registers natively in test_native_evidence_registers_are_fenced_and_insert_only). Not covered: sensitivity and retention, verification and dispute, repository search, annotations, links to findings and decisions, external-reference checking, an S3-compatible backend and a backup of the object volume.",
        [
            "apps/api/impact_api/object_store.py",
            "apps/api/impact_api/content_safety.py",
            "apps/api/impact_api/evidence.py",
            "apps/api/impact_api/evidence_contracts.py",
            "infrastructure/migrations/0023_evidence_objects.sql",
            "qualification/test_evidence.py",
            "qualification/test_evidence_unit.py",
            "apps/web/src/Evidence.tsx",
            "docs/RELEASE-0.22.md",
            "tools/browser/evidence-check.mjs",
            "docs/evidence/evidence-browser-tests.json",
        ],
    ),
    (
        "FR-SEC-005",
        "v0.22 checks evidence uploads before any byte is accepted and again on the bytes: an allow-list of media types (PDF, PNG, JPEG, plain text, CSV), a plain file name whose single extension the declared type permits, a declared size (at most 25,000,000 bytes) and SHA-256 matched exactly, magic bytes matched to the declared type, executables and PDFs naming active content refused, text required to be UTF-8 without leading markup; a scan verdict precedes any download and a FAILED or INFECTED blob, or bytes that no longer hash to the recorded digest, are never served (test_evidence.py::test_allow_list_names_and_declared_size_are_refused_before_any_byte, test_magic_bytes_size_and_digest_are_checked, test_eicar_is_infected_rejected_and_never_downloadable, test_failed_scan_and_changed_bytes_are_never_served, test_replay_resumes_a_scan_interrupted_after_the_seal, test_raw_upload_route_alone_exceeds_the_json_cap; test_evidence_unit.py). The shipped scanners are not anti-malware engines (eicar-signature recognises only the EICAR test file). Not covered: a real scanning engine, archive expansion and macro profiles (the FT-SEC-005 archive fixture), password-protected files, previews and re-encoding, multipart uploads and external fetch validation.",
        [
            "apps/api/impact_api/object_store.py",
            "apps/api/impact_api/content_safety.py",
            "apps/api/impact_api/evidence.py",
            "apps/api/impact_api/evidence_contracts.py",
            "infrastructure/migrations/0023_evidence_objects.sql",
            "qualification/test_evidence.py",
            "qualification/test_evidence_unit.py",
            "apps/web/src/Evidence.tsx",
            "docs/RELEASE-0.22.md",
            "tools/browser/evidence-check.mjs",
            "docs/evidence/evidence-browser-tests.json",
        ],
    ),
    (
        "FR-ANA-004",
        "Calculated results carry lineage, coverage and stale flags (v0.7, v0.19). v0.24 adds a read-only programme dashboard and indicator series in which every value distinguishes OFFICIAL (only from this programme's locked snapshot) from PROVISIONAL, exposes lock time, calculation times, last source change and coverage from the period's obligation set (zero required is not applicable, never 100 percent), and stays marked stale under a stated rule until recalculated or re-closed; a read never makes a value fresh (qualification/test_dashboards.py::test_provisional_to_official_and_freshness_transitions, test_official_pooled_ratio_from_the_programme_snapshot, test_coverage_with_no_required_obligation_is_not_applicable; dashboard-browser check). Not covered: export with embedded context (FT-ANA-004's export half), external source refresh state (no connectors exist), dashboard authoring and saved dashboards.",
        [
            "apps/api/impact_api/domain.py",
            "apps/api/impact_api/service.py",
            "qualification/test_measurement.py",
            "apps/api/impact_api/dashboards.py",
            "apps/api/impact_api/dashboard_contracts.py",
            "qualification/test_dashboards.py",
            "apps/web/src/Dashboards.tsx",
            "tools/browser/dashboard-check.mjs",
            "docs/evidence/dashboard-browser-tests.json",
            "docs/RELEASE-0.24.md",
        ],
    ),
    (
        "FR-SEC-007",
        "Implemented routes enforce explicit grants, tenant fences, natural-person independence, revisions and retry receipts; audit events are written in the same transaction as every command and object revisions carry a payload SHA-256. v0.25 part A adds a tamper-evident audit export (create_audit_export, purpose-required, 300 s fresh assurance, audited): JSON Lines ordered by occurrence with a hash chain across pages, a manifest with the content SHA-256 and an HMAC seal under a key derived from the current cookie secret, and verify functions that detect a changed, removed or reordered line and a changed manifest (qualification/test_audit_export.py::test_chain_digest_and_seal_verify_and_detect_tampering, test_export_pages_verify_and_each_export_is_audited). The seal is verifiable by the platform only while its key is current or in grace; it is not a public signature. Native concurrency evidence is limited to qualification/test_native_concurrency.py (v0.14). Not covered: tamper evidence of the stored audit table itself (an operator with database ownership can alter rows), external anchoring, a durable export register.",
        [
            "apps/api/impact_api/store.py",
            "apps/api/impact_api/auth.py",
            "qualification/test_live_application.py",
            "apps/api/impact_api/audit_export.py",
            "apps/api/impact_api/audit_export_contracts.py",
            "qualification/test_audit_export.py",
            "docs/RELEASE-0.25a.md",
        ],
    ),
    (
        "FR-SEC-002",
        "v0.25 part A: the application's own secrets (cookie, invitation signing, delivery sealing) are versioned keyrings with grace secrets and a key id (12 hex characters of SHA-256 over family and secret) carried in CSRF tokens, signed cursors and the header of sealed delivery recipients and logout hints; new values always use the current secret, values made before a rotation keep working while their secret is in grace and fail once it is retired, legacy unheaded values still open, and a missing key answers a controlled failure (RECIPIENT_UNREADABLE, logout without hint), never plaintext (qualification/test_key_rotation.py::test_sealed_recipients_carry_the_kid_and_legacy_values_still_open, test_logout_hints_rotate_and_an_oversized_token_is_not_sealed, test_values_made_before_rotation_work_during_grace_and_fail_after_retirement, test_delivery_and_invitation_secrets_rotate_for_the_worker). docs/current/KEY-AND-ENCRYPTION-REGISTER.md inventories every secret, its kid, holders and grace, the keys the application does not hold, and states plainly what is not encrypted by the application (database files, the evidence object store, dumps and backup sets, captured mail, logs). Not covered: encryption at rest under a platform data-protection key, rotation of such a key over backups (FT-SEC-002), KMS or HSM custody, Keycloak signing-key rotation (documented, not exercised), an operator interface showing key status.",
        [
            "apps/api/impact_api/keyring.py",
            "apps/api/impact_api/delivery.py",
            "apps/api/impact_api/auth.py",
            "apps/api/impact_api/config.py",
            "qualification/test_key_rotation.py",
            "docs/current/KEY-AND-ENCRYPTION-REGISTER.md",
            "docs/RELEASE-0.25a.md",
        ],
    ),
    (
        "FR-SEC-006",
        "v0.25 part A: rotation and retirement of the application secrets are explicit operations (scripts/rotate_secrets.py status, rotate, retire, dry run; deploy/rotate-secrets.sh on the server under the deployment lock, recreating the API and worker) with atomic 0600 writes and a register beside the secrets file that names kids, dates, actor and reason, never a value; old values are rejected after retirement; settings refuse short, repeated or shared secrets and keep every secret and DSN out of their repr; no value reaches the rotation output, responses, logs or the API log (qualification/test_key_rotation.py::test_env_file_rotation_is_atomic_private_and_prints_kids_only, test_settings_validate_keyrings_and_never_print_secrets, test_values_made_before_rotation_work_during_grace_and_fail_after_retirement; the CI container-stack job rotates every family, smokes, retires, smokes and compares every secrets.env value with what was printed). Not covered: connector credentials and credential references with fingerprints in an admin view (no connectors exist), configuration export, automatic rotation and expiry alerts, database passwords and TLS keys (outside the keyrings).",
        [
            "apps/api/impact_api/keyring.py",
            "apps/api/impact_api/config.py",
            "scripts/rotate_secrets.py",
            "deploy/rotate-secrets.sh",
            "qualification/test_key_rotation.py",
            "docs/current/KEY-AND-ENCRYPTION-REGISTER.md",
            "docs/RELEASE-0.25a.md",
        ],
    ),
    (
        "VF-AUD-001",
        "v0.25 part A: a permitted audit export (create_audit_export; capability audit.export for OWNER and TENANT_ADMIN, purpose-required with SECURITY_REVIEW, INCIDENT_INVESTIGATION, REGULATORY_REQUEST or INTERNAL_AUDIT, fresh assurance 300 s) returns the tenant's audit events of an ended window of at most 366 days as JSON Lines (projected audit columns and the revision digest only: no payload, secret, sealed value or address) with a manifest, a hash chain and a seal, paged by a signed cursor bound to tenant, principal, window and purpose; each page is itself an audited command with a receipt, so receipts reconcile to the export's own events (qualification/test_audit_export.py::test_export_pages_verify_and_each_export_is_audited, test_exact_retry_is_identical_and_a_changed_payload_conflicts, test_refusals_tenant_capability_assurance_and_revocation, test_purpose_is_required_and_a_purpose_bound_grant_authorises_only_its_purpose, test_owner_may_export_and_the_content_holds_no_secret, test_cursor_is_signed_and_bound_to_window_and_purpose). Not covered, so the gate is not met: every audit event class of FSD section 35 (denied operations and restricted reads are not recorded as events), the 365-day metadata retention and governed business retention, search by reviewers beyond a window export, and a durable export register (the window and digest live in the 7-day receipt).",
        [
            "apps/api/impact_api/audit_export.py",
            "apps/api/impact_api/audit_export_contracts.py",
            "apps/web/src/AuditExport.tsx",
            "qualification/test_audit_export.py",
            "docs/RELEASE-0.25a.md",
        ],
    ),
    (
        "FR-PRV-007",
        "v0.25 part B: data-subject request cases for a member of the tenant (no participant records exist): intake with request type ACCESS or ERASURE, subject membership, reason, verification note and handling authority, purpose-bound to DATA_SUBJECT_REQUEST (a purpose-less grant never authorises), independent approval by a natural person other than every author and the subject against the SHA-256 of the per-store plan they reviewed, and an access response that is one canonical export package with a manifest (per-section count, completeness and SHA-256), holding only the subject's data, downloaded through a mediated, logged, purpose-bound route and expiring after 7 days (qualification/test_privacy_requests.py::test_access_export_holds_only_the_subjects_data_with_a_manifest_and_is_mediated, test_case_approval_requires_an_independent_natural_person, test_case_operations_are_purpose_bound_and_never_authorised_by_a_general_grant, test_exact_retry_changed_payload_stale_revision_and_changed_plan). Not covered: participants and household members, a response-deadline policy, rejected and on-hold outcomes chosen by the handler, a subject channel or self-service, free text other members wrote about the subject.",
        [
            "apps/api/impact_api/privacy.py",
            "apps/api/impact_api/privacy_contracts.py",
            "infrastructure/migrations/0027_privacy_execution.sql",
            "qualification/test_privacy_requests.py",
            "apps/web/src/Privacy.tsx",
            "docs/RELEASE-0.25b.md",
        ],
    ),
    (
        "FR-PRV-005",
        "v0.25 part B: an erasure case is executed only from its independently approved, enumerated per-store plan (member profile, invitation register and revisions, revision payloads, projections, delivery intents, object-store bytes), re-computed and compared by SHA-256 at execution; each store action records its own outcome, an item under an active retention_hold or still used by another evidence revision is HELD with its review date, a failed object-store deletion leaves the case PartiallyCompleted until a retry completes it, and revision payloads are removable only through the definer privacy_remove_revisions under revision_removal_guard with a deletion_ledger row (qualification/test_privacy_requests.py::test_erasure_reaches_every_store_keeps_audit_and_never_alters_official_numbers, test_erasure_reports_held_items_and_a_failed_object_store_deletion_until_retried, test_erasure_of_a_named_import_batch_removes_its_raw_content, test_revision_removal_is_reachable_only_through_an_approved_executing_plan). Not covered: an API to place or release holds (tests insert them), restriction before deletion, anonymisation, derivatives beyond the listed stores, deletion handling in backups (FR-PRV-006).",
        [
            "apps/api/impact_api/privacy.py",
            "apps/api/impact_api/object_store.py",
            "infrastructure/migrations/0027_privacy_execution.sql",
            "qualification/test_privacy_requests.py",
            "docs/RELEASE-0.25b.md",
        ],
    ),
    (
        "VF-PRV-001",
        "v0.25 part B: an approved erasure removes or restricts the subject's data in active primary records, projections, sealed delivery addresses (overwritten with random bytes and the intents SUPERSEDED with the lease generation advanced), object-store bytes (after the commit, recorded per object) and named import raw content within the request, keeps audit, identifiers and every official number unchanged (every CalculatedResult, Snapshot and Observation revision compared before and after), and reports a no-hold, a partial-hold and a failed-derivative-store run distinctly (qualification/test_privacy_requests.py::test_erasure_reaches_every_store_keeps_audit_and_never_alters_official_numbers, test_erasure_reports_held_items_and_a_failed_object_store_deletion_until_retried; natively test_native_privacy_tables_are_fenced_for_the_application_login). Not covered: backup expiry and deletion replay on restore (FR-PRV-006, TH27; erased values stay in nightly sets until they age out), search, AI and cache stores (none exist), external recipients of earlier publications.",
        [
            "apps/api/impact_api/privacy.py",
            "infrastructure/migrations/0027_privacy_execution.sql",
            "qualification/test_privacy_requests.py",
            "docs/RELEASE-0.25b.md",
        ],
    ),
    (
        "FR-OPS-006",
        "Operations hardening (October 2026), staging server only: nightly backup sets hold the application and identity-provider databases, the roles without passwords, the evidence object volume and a SHA-256 manifest, are verified before they are published and kept 7 daily and 4 weekly; a weekly restore drill restores the newest complete set into throwaway containers and refuses to declare success unless every object matches its digest, every blob row finds its object, the migrator finds every ledgered checksum, ownership and forced fences are intact and the realm is present, recording duration and backup age (deploy/backup.sh, deploy/restore-drill.sh, deploy/drill_restore.sh, deploy/restore_check.py; qualification/test_ops_unit.py::test_backup_set_holds_databases_roles_objects_and_a_verified_manifest, test_disk_guard_refuses_and_reports_without_touching_the_sets, test_drill_restore_reports_a_damaged_set_or_a_failed_restore, test_object_digests_match_names_and_blob_rows_find_their_objects, test_drill_record_measures_duration_and_backup_age; the CI container-stack job takes a set, restores it and runs the drill with every check passing). Not covered: an off-server or immutable copy (sets share the server's disk and root account), reconciliation of accepted writes and reapplication of deletions and revocations before controlled reopening, comparison of effective grants and report snapshots against the source, recovery region and key policy, and a representative tenant's full recovery; no RPO or RTO target is met.",
        [
            "deploy/backup.sh",
            "deploy/restore-drill.sh",
            "deploy/drill_restore.sh",
            "deploy/restore_check.py",
            "deploy/compose.yaml",
            "qualification/test_ops_unit.py",
            "docs/current/DEPLOYMENT-GUIDE.md",
            "docs/RELEASE-OPS-2026-10.md",
        ],
    ),
    (
        "VF-OBS-001",
        "Alerting clause only. Operations hardening (October 2026): a check every five minutes (systemd timer on the server, and after each deployment and drill) raises closed alert codes for missing, stale, failed or disk-refused backups, low disk, an unhealthy or absent container, a stale worker heartbeat, DEAD deliveries, a queue backlog, a schema mismatch, an unavailable summary and a failed or stale restore drill, writes them into deploy-status.json with secret values scrubbed, and an injected failure (worker stopped) is alerted by the next check and cleared after restart (deploy/ops-check.sh, deploy/ops_alerts.py; qualification/test_ops_unit.py::test_a_healthy_server_has_no_alerts, test_each_problem_raises_its_alert, test_evaluate_writes_the_ops_file_and_merges_into_the_status_files, test_host_units_run_the_check_every_five_minutes_and_the_drill_weekly; CI container-stack step 'An injected failure (worker stopped) is alerted by the next check'). Every request already carries a correlation identifier returned in errors. Not covered: correlation references traced across jobs and integrations, tenant-scoped diagnosis and audit separation of logs, any notification channel (alerts reach only the status page; nobody is paged), metric history.",
        [
            "deploy/ops-check.sh",
            "deploy/ops_alerts.py",
            "deploy/update.sh",
            "qualification/test_ops_unit.py",
            "docs/RELEASE-OPS-2026-10.md",
        ],
    ),
    (
        "VF-UX-001",
        "QA 2026-10 (tools/browser/a11y-check.mjs, group a11y-browser) scans 43 page states of the web client (every workspace area and tab, record and decision dialogs, tenant lifecycle, Workers, recovery contacts, initial access, authority renewal, sign-in, one 390 px state) with axe-core 4.13.0 at the WCAG 2.0/2.1/2.2 A and AA tags: 0 serious or critical violations and no accepted exceptions after the fixes (759 colour-contrast nodes before). A scripted keyboard-only flow submits an observation and has an independent reviewer approve it, and checks focus visibility (outline contrast at least 3:1), dialog focus containment and return, tab-list arrow keys and the skip link. Chromium 153 only. Not covered, so the failure rule (a clean automated scan alone does not pass) is not met: screen-reader review, other browsers, zoom and reflow at 400 percent, a manual WCAG 2.2 AA audit, the identity-provider pages, generated report templates, the invalid-field and stale-revision cases and keyboard walk-throughs of the other processes.",
        [
            "tools/browser/a11y-check.mjs",
            "docs/evidence/a11y-browser-tests.json",
            "docs/current/ACCESSIBILITY-STATEMENT.md",
            "docs/QA-A11Y-2026-10.md",
        ],
    ),
]
# Requirements that stay PENDING, with what the latest increments do and do not show for them.
pending_notes = {
    "FR-PRV-004": "PENDING. Related v0.25 part B evidence, recorded so that it is not mistaken for coverage: the worker runs one fixed retention schedule for every tenant (job class RETENTION_SWEEP; operation receipts past their 7-day window deleted, OPEN uploads past 24 hours expired, privacy export packages deleted after 7 days, sealed delivery addresses redacted 30 days after a final state), each class with its own trigger, duration and action, and writes one insert-only retention_proof row per class (qualification/test_retention.py::test_sweep_removes_only_expired_items_and_proves_each_class). There are no tenant retention policies with purpose and owner, no preview of affected objects and holds, no approval gate before collection and no record or evidence class, so the validation and acceptance text (a 90-day diagnostic-log class and a separate approved evidence term) is not exercised. Retain the original acceptance criteria; this requirement remains open.",
    "VF-PRV-002": "PENDING. Related v0.25 part B evidence: scheduled action receipts exist for four fixed data classes (retention_proof with cutoff on the database clock, affected count and the SHA-256 of the sorted affected keys, written by a lease-fenced sweep that a stale holder cannot complete; qualification/test_retention.py::test_sweep_removes_only_expired_items_and_proves_each_class, test_a_stale_lease_holder_neither_deletes_nor_proves, test_a_sweep_that_keeps_failing_backs_off_then_fails_with_an_error_class, test_worker_holds_exactly_the_retention_privileges). Approved record and evidence policies before collection, diagnostic-log, AI-content and security-metadata classes and orphan-copy detection do not exist, so the target is not met. Retain the original acceptance criteria; this requirement remains open.",
    "FR-IAM-007": "PENDING. Related v0.16 evidence, recorded so that it is not mistaken for coverage: the nominee of a recovery contact can confirm the registered email address with a single-use eight-digit code (channel-request/channel-confirm; 15-minute expiry, 5 attempts, at most 3 requests per contact per hour; the code is derived, never stored, and only its keyed hash is kept; qualification/test_worker.py). That verifies a channel for contact evidence only; it is not an identity change, a lost-factor recovery or a support path, and no test exercises the validation text (no support reset refusal, no restricted recovery case, no withheld privileges pending verification). Retain the original acceptance criteria; this requirement remains open.",
    "FR-ACC-008": "PENDING. Not touched by v0.16 although the delivery plan listed it for that increment: no support case, elevation grant, support session or tenant-ended access exists. The v0.16 worker runs on its own login and writes reminder notices as a per-tenant SERVICE principal without identity, membership or grant; that is not support access. Retain the original acceptance criteria; this requirement remains open.",
    "VF-IAM-001": "PENDING. v0.15 revokes browser sessions immediately on logout and on a verified back-channel logout token (qualification/test_live_idp.py, test_backchannel_logout.py), but the 60-second bound is not met or measured: bearer access tokens remain valid until exp (120 s in the qualification realm) after a provider logout, no revocation latency is measured from platform receipt, and suspension, grant removal, service credentials, generated downloads, search, AI and queued jobs are not polled (most of them do not exist). v0.16's worker re-reads each delivery intent immediately before sending and supersedes it when the invitation generation, the recovery-channel challenge or the notice recipient is no longer current (qualification/test_worker.py); that is a recheck of the intent, not a measured revocation bound, and no sensitive job class exists for the worker to reauthorise. Retain the original acceptance criteria; this requirement remains open.",
    "VF-PER-005": "PENDING. v0.23 renders PDF, XLSX and DOCX exports of a frozen package through the worker with acknowledgement as one synchronous transaction, job state as progress and cancellation before start (qualification/test_report_exports.py::test_export_request_is_one_queued_job_with_receipt_audit_and_exact_retry, test_cancellation_before_start_is_honoured_and_nothing_is_rendered); that is functional evidence only. No 100,000-row export, 50-page report, twenty-chart report, p95 or mixed-load measurement has been executed. Retain the original acceptance criteria; this requirement remains open.",
    "VF-PER-006": "PENDING. v0.24's dashboard reads are uncached and computed per request, so after approval and calculation the next read reflects the new value, and the freshness block separates calculation and lock times (qualification/test_dashboards.py::test_provisional_to_official_and_freshness_transitions); that is functional evidence only. No 60-second p95 timing, load or separate display of review delay has been measured. Retain the original acceptance criteria; this requirement remains open.",
}
partial = {key: (description, evidence) for ids, description, evidence in groups for key in ids.split()}
requirements = []
for group in ["functional", "nonfunctional"]:
    for req in catalogue[group]:
        description, evidence = partial.get(
            req["id"],
            (
                pending_notes.get(
                    req["id"],
                    "No complete implementation and acceptance evidence mapped. Retain the original acceptance criteria; this requirement remains open.",
                ),
                [],
            ),
        )
        requirements.append(
            {
                **req,
                "category": group,
                "status": "PARTIAL" if req["id"] in partial else "PENDING",
                "assessment": description,
                "evidence_paths": evidence,
                "release_gate": "Complete the original acceptance criteria and record passing implementation and qualification evidence.",
            }
        )
assert len(requirements) == 307 and len({r["id"] for r in requirements}) == 307
assert set(partial) <= {r["id"] for r in requirements}
assert not set(pending_notes) & set(partial)
for requirement in requirements:
    for path in requirement["evidence_paths"]:
        assert (ROOT / path).is_file(), path
summary = dict(Counter(r["status"] for r in requirements))
result = {
    "build": json.loads((ROOT / "VERSION.json").read_text())["build"],
    "assessment_date": "2026-10-01",
    "enterprise_complete": False,
    "method": "PARTIAL means tested behavior exists for a bounded subset; PENDING does not imply that a scaffold or design contract is an implementation. No enterprise acceptance is inferred from passing subset tests.",
    "summary": summary,
    "requirements": requirements,
}
(ROOT / "docs/COMPLETION-LEDGER.json").write_text(json.dumps(result, indent=2) + "\n")
lines = [
    "# Requirement completion ledger",
    "",
    result["method"],
    "",
    f"Scope: 270 functional requirements and 37 non-functional qualification requirements. Status: {summary}. Enterprise completion: **false**.",
    "",
    "| Requirement | Title | Status | Evidence |",
    "|---|---|---|---|",
]
for req in requirements:
    paths = ", ".join(f"[{Path(p).name}](../{p})" for p in req["evidence_paths"])
    lines.append(f"| {req['id']} | {req['title']} | {req['status']} | {paths or 'Pending'} |")
(ROOT / "docs/COMPLETION-LEDGER.md").write_text("\n".join(lines) + "\n")
print(json.dumps(summary))
